import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import * as warehouseDocumentService from '../../../services/admin/warehouse-documents.service';

export async function registerWarehouseDocumentRoutes(fastify: FastifyInstance) {
  // GET /admin/warehouse/documents
  fastify.get('/documents', {
    schema: {
      tags: ['warehouse'],
      summary: 'Lista dokumentów magazynowych',
      querystring: {
        type: 'object',
        properties: {
          page: { type: 'integer', minimum: 1, default: 1 },
          limit: { type: 'integer', minimum: 1, maximum: 100, default: 20 },
          search: { type: 'string' },
          type: { type: 'string', enum: ['PZ', 'ZH', 'PW', 'WZ', 'ZW', 'RW', 'INW'] },
          status: { type: 'string', enum: ['DRAFT', 'CONFIRMED', 'CANCELLED'] },
          dateFrom: { type: 'string' },
          dateTo: { type: 'string' },
          isAutoGenerated: { type: 'boolean' },
          stockWarning: { type: 'boolean' },
        },
      },
    },
  }, async (request: FastifyRequest<{ Querystring: warehouseDocumentService.DocumentsQuery }>, reply: FastifyReply) => {
    try {
      const result = await warehouseDocumentService.getDocuments(request.query);
      return reply.send(result);
    } catch (error) {
      fastify.log.error(error);
      return reply.status(500).send({ error: 'Internal Server Error', message: 'Nie udało się pobrać dokumentów' });
    }
  });

  // POST /admin/warehouse/documents
  fastify.post('/documents', {
    schema: {
      tags: ['warehouse'],
      summary: 'Utwórz dokument magazynowy (DRAFT)',
      body: {
        type: 'object',
        required: ['type', 'items'],
        properties: {
          type: { type: 'string', enum: ['PZ', 'ZH', 'PW', 'WZ', 'ZW', 'RW', 'INW'] },
          date: { type: 'string' },
          description: { type: 'string' },
          orderId: { type: 'string' },
          isAutoGenerated: { type: 'boolean' },
          metadataJson: { type: 'object', additionalProperties: true },
          items: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              required: ['productId'],
              properties: {
                productId: { type: 'string' },
                quantity: { type: 'number', minimum: 0 },
                systemQuantity: { type: ['number', 'null'], minimum: 0 },
                barcodeId: { type: 'string' },
                scannedEan: { type: 'string' },
                baseQuantity: { type: 'number', minimum: 0 },
                quantityMultiplier: { type: 'number', exclusiveMinimum: 0 },
                unitPrice: { type: 'number', minimum: 0 },
                notes: { type: 'string' },
                reservationId: { type: ['string', 'null'] },
              },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest<{ Body: warehouseDocumentService.CreateDocumentInput }>, reply: FastifyReply) => {
    try {
      const doc = await warehouseDocumentService.createDocument(request.body);
      return reply.status(201).send(doc);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd tworzenia dokumentu';
      return reply.status(400).send({ error: 'Bad Request', message });
    }
  });

  // GET /admin/warehouse/documents/:id
  fastify.get('/documents/:id', {
    schema: { tags: ['warehouse'], summary: 'Szczegóły dokumentu' },
  }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    try {
      const doc = await warehouseDocumentService.getDocumentById(request.params.id);
      if (!doc) return reply.status(404).send({ error: 'Not Found', message: 'Dokument nie znaleziony' });
      return reply.send(doc);
    } catch (error) {
      fastify.log.error(error);
      return reply.status(500).send({ error: 'Internal Server Error', message: 'Błąd pobierania dokumentu' });
    }
  });

  // PUT /admin/warehouse/documents/:id
  fastify.put('/documents/:id', {
    schema: {
      tags: ['warehouse'],
      summary: 'Edytuj dokument (tylko DRAFT)',
      body: {
        type: 'object',
        properties: {
          date: { type: 'string' },
          description: { type: 'string' },
          orderId: { type: ['string', 'null'] },
          items: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              required: ['productId'],
              properties: {
                productId: { type: 'string' },
                quantity: { type: 'number', minimum: 0 },
                systemQuantity: { type: ['number', 'null'], minimum: 0 },
                barcodeId: { type: 'string' },
                scannedEan: { type: 'string' },
                baseQuantity: { type: 'number', minimum: 0 },
                quantityMultiplier: { type: 'number', exclusiveMinimum: 0 },
                unitPrice: { type: 'number', minimum: 0 },
                notes: { type: 'string' },
                reservationId: { type: ['string', 'null'] },
              },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest<{ Params: { id: string }; Body: warehouseDocumentService.UpdateDocumentInput }>, reply: FastifyReply) => {
    try {
      const doc = await warehouseDocumentService.updateDocument(request.params.id, request.body);
      return reply.send(doc);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd edycji dokumentu';
      const status = message.includes('nie znaleziony') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });

  fastify.post('/documents/zh/providers/:providerId/export-csv', {
    schema: {
      tags: ['warehouse'],
      summary: 'Wygeneruj CSV roboczych zamówień hurtowych ZH dostawcy i zatwierdź je',
      params: {
        type: 'object',
        required: ['providerId'],
        properties: { providerId: { type: 'string' } },
      },
    },
  }, async (request: FastifyRequest<{ Params: { providerId: string } }>, reply: FastifyReply) => {
    try {
      const result = await warehouseDocumentService.exportWholesaleOrdersForProviderCsv(request.params.providerId);
      return reply.send(result);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd eksportu CSV zamówienia hurtowego';
      return reply.status(400).send({ error: 'Error', message });
    }
  });

  fastify.post('/documents/:id/items/merge', {
    schema: {
      tags: ['warehouse'],
      summary: 'Dodaj albo zwiększ pozycję dokumentu DRAFT',
      params: {
        type: 'object',
        required: ['id'],
        properties: { id: { type: 'string' } },
      },
      body: {
        type: 'object',
        required: ['productId'],
        properties: {
          productId: { type: 'string' },
          quantity: { type: 'number', minimum: 0 },
          systemQuantity: { type: ['number', 'null'], minimum: 0 },
          barcodeId: { type: 'string' },
          scannedEan: { type: 'string' },
          baseQuantity: { type: 'number', minimum: 0 },
          quantityMultiplier: { type: 'number', exclusiveMinimum: 0 },
          unitPrice: { type: 'number', minimum: 0 },
          notes: { type: 'string' },
          reservationId: { type: ['string', 'null'] },
        },
      },
    },
  }, async (request: FastifyRequest<{
    Params: { id: string };
    Body: warehouseDocumentService.DocumentItemInput;
  }>, reply: FastifyReply) => {
    try {
      const doc = await warehouseDocumentService.mergeDocumentItem(request.params.id, request.body);
      return reply.send(doc);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd dodawania pozycji dokumentu';
      const status = message.includes('nie znalezion') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });

  fastify.patch('/documents/:id/items/:itemId', {
    schema: {
      tags: ['warehouse'],
      summary: 'Edytuj pozycję dokumentu DRAFT',
      params: {
        type: 'object',
        required: ['id', 'itemId'],
        properties: {
          id: { type: 'string' },
          itemId: { type: 'string' },
        },
      },
      body: {
        type: 'object',
        properties: {
          quantity: { type: 'number', minimum: 0 },
          systemQuantity: { type: ['number', 'null'], minimum: 0 },
          baseQuantity: { type: ['number', 'null'], exclusiveMinimum: 0 },
          quantityMultiplier: { type: ['number', 'null'], exclusiveMinimum: 0 },
          unitPrice: { type: ['number', 'null'], minimum: 0 },
          notes: { type: ['string', 'null'] },
        },
      },
    },
  }, async (request: FastifyRequest<{
    Params: { id: string; itemId: string };
    Body: warehouseDocumentService.UpdateDocumentItemInput;
  }>, reply: FastifyReply) => {
    try {
      const doc = await warehouseDocumentService.updateDocumentItem(request.params.id, request.params.itemId, request.body);
      return reply.send(doc);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd edycji pozycji dokumentu';
      const status = message.includes('nie znalezion') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });

  fastify.delete('/documents/:id/items/:itemId', {
    schema: {
      tags: ['warehouse'],
      summary: 'Usuń pozycję dokumentu DRAFT',
      params: {
        type: 'object',
        required: ['id', 'itemId'],
        properties: {
          id: { type: 'string' },
          itemId: { type: 'string' },
        },
      },
    },
  }, async (request: FastifyRequest<{ Params: { id: string; itemId: string } }>, reply: FastifyReply) => {
    try {
      const doc = await warehouseDocumentService.deleteDocumentItem(request.params.id, request.params.itemId);
      return reply.send(doc);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd usuwania pozycji dokumentu';
      const status = message.includes('nie znalezion') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });

  fastify.post('/documents/:id/export-csv', {
    schema: {
      tags: ['warehouse'],
      summary: 'Wygeneruj CSV zamówienia hurtowego ZH i zatwierdź dokument roboczy',
      params: {
        type: 'object',
        required: ['id'],
        properties: { id: { type: 'string' } },
      },
    },
  }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    try {
      const result = await warehouseDocumentService.exportWholesaleOrderCsv(request.params.id);
      return reply.send(result);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd eksportu CSV zamówienia hurtowego';
      const status = message.includes('nie znaleziony') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });

  // POST /admin/warehouse/documents/:id/confirm
  fastify.post('/documents/:id/confirm', {
    schema: { tags: ['warehouse'], summary: 'Zatwierdź dokument (DRAFT → CONFIRMED)' },
  }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    try {
      const doc = await warehouseDocumentService.confirmDocument(request.params.id);
      return reply.send(doc);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd zatwierdzania dokumentu';
      const status = message.includes('nie znaleziony') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });

  fastify.post('/documents/:id/create-pz', {
    schema: {
      tags: ['warehouse'],
      summary: 'Utwórz roboczy PZ z zamówienia hurtowego ZH',
      params: {
        type: 'object',
        required: ['id'],
        properties: { id: { type: 'string' } },
      },
    },
  }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    try {
      const result = await warehouseDocumentService.createPzFromWholesaleOrder(request.params.id);
      return reply.status(result.created ? 201 : 200).send(result);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd tworzenia PZ z zamówienia hurtowego';
      const status = message.includes('nie znaleziony') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });

  // POST /admin/warehouse/documents/:id/cancel
  fastify.post('/documents/:id/cancel', {
    schema: {
      tags: ['warehouse'],
      summary: 'Anuluj dokument',
      body: {
        type: 'object',
        properties: {
          reason: { type: 'string' },
        },
      },
    },
  }, async (request: FastifyRequest<{ Params: { id: string }; Body: warehouseDocumentService.CancelDocumentInput }>, reply: FastifyReply) => {
    try {
      const doc = await warehouseDocumentService.cancelDocument(request.params.id, request.body ?? {});
      return reply.send(doc);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd anulowania dokumentu';
      const status = message.includes('nie znaleziony') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });

  // DELETE /admin/warehouse/documents/:id
  fastify.delete('/documents/:id', {
    schema: { tags: ['warehouse'], summary: 'Usuń dokument (tylko DRAFT)' },
  }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    try {
      await warehouseDocumentService.deleteDocument(request.params.id);
      return reply.status(204).send();
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Błąd usuwania dokumentu';
      const status = message.includes('nie znaleziony') ? 404 : 400;
      return reply.status(status).send({ error: 'Error', message });
    }
  });
}
