import { Prisma } from '@prisma/client';
import prisma from '../../lib/prisma';
import { getTenantId } from '../../lib/tenant-context';
import { addStockSyncJob } from '../queue/stock-sync.queue';

type StockSyncStatus = 'PENDING' | 'PROCESSING' | 'SUCCESS' | 'FAILED';
type DocumentType = 'PZ' | 'PW' | 'WZ' | 'RW';

export interface StockSyncLogsQuery {
  page?: number;
  limit?: number;
  shopId?: string;
  warehouseProductId?: string;
  status?: StockSyncStatus;
  dateFrom?: string;
  dateTo?: string;
}

export interface ProductMovementsQuery {
  page?: number;
  limit?: number;
  status?: 'DRAFT' | 'CONFIRMED' | 'CANCELLED';
  type?: DocumentType;
  dateFrom?: string;
  dateTo?: string;
}

export interface StockDiscrepanciesQuery {
  includeZero?: boolean;
}

function requireTenantId() {
  const tenantId = getTenantId();
  if (!tenantId) throw new Error('Brak kontekstu tenanta');
  return tenantId;
}

export async function getStockSyncLogs(query: StockSyncLogsQuery = {}) {
  const tenantId = requireTenantId();
  const { page = 1, limit = 50, shopId, warehouseProductId, status, dateFrom, dateTo } = query;
  const skip = (page - 1) * limit;

  const where: Prisma.StockSyncLogWhereInput = { tenantId };
  if (shopId) where.shopId = shopId;
  if (warehouseProductId) where.warehouseProductId = warehouseProductId;
  if (status) where.status = status;
  if (dateFrom || dateTo) {
    where.createdAt = {};
    if (dateFrom) where.createdAt.gte = new Date(dateFrom);
    if (dateTo) where.createdAt.lte = new Date(dateTo);
  }

  const [data, total] = await Promise.all([
    prisma.stockSyncLog.findMany({
      where,
      skip,
      take: limit,
      orderBy: { createdAt: 'desc' },
      include: {
        warehouseProduct: { select: { id: true, sku: true, name: true, currentStock: true } },
        shop: { select: { id: true, name: true, platform: true, status: true } },
        document: { select: { id: true, number: true, type: true, status: true, date: true } },
      },
    }),
    prisma.stockSyncLog.count({ where }),
  ]);

  return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
}

export async function retryStockSyncLog(id: string) {
  const tenantId = requireTenantId();
  const log = await prisma.stockSyncLog.findFirst({
    where: { id, tenantId },
    include: { warehouseProduct: true, shop: true },
  });

  if (!log) throw new Error('Log synchronizacji stanu nie znaleziony');

  const mapping = await prisma.shopProductMapping.findFirst({
    where: {
      tenantId,
      shopId: log.shopId,
      warehouseProductId: log.warehouseProductId,
      isActive: true,
      shop: { status: 'ACTIVE' },
    },
  });

  if (!mapping) {
    throw new Error('Brak aktywnego mapowania produktu do sklepu dla ponowienia synchronizacji');
  }

  const retryLog = await prisma.stockSyncLog.create({
    data: {
      tenantId,
      warehouseProductId: log.warehouseProductId,
      shopId: log.shopId,
      triggeredBy: 'MANUAL',
      documentId: log.documentId,
      stockBefore: log.stockAfter,
      stockAfter: log.warehouseProduct.currentStock,
      status: 'PENDING',
    },
  });

  await addStockSyncJob({
    logId: retryLog.id,
    tenantId,
    warehouseProductId: log.warehouseProductId,
    shopId: log.shopId,
    externalProductId: mapping.externalProductId,
    triggeredBy: 'MANUAL',
    documentId: log.documentId ?? undefined,
  });

  return retryLog;
}

export async function getProductMovements(productId: string, query: ProductMovementsQuery = {}) {
  const tenantId = requireTenantId();
  const product = await prisma.warehouseProduct.findFirst({
    where: { id: productId, tenantId },
    include: { catalog: true },
  });
  if (!product) throw new Error('Produkt nie znaleziony');

  const { page = 1, limit = 50, status, type, dateFrom, dateTo } = query;
  const skip = (page - 1) * limit;

  const documentWhere: Prisma.WarehouseDocumentWhereInput = { tenantId };
  if (status) documentWhere.status = status;
  if (type) documentWhere.type = type;
  if (dateFrom || dateTo) {
    documentWhere.date = {};
    if (dateFrom) documentWhere.date.gte = new Date(dateFrom);
    if (dateTo) documentWhere.date.lte = new Date(dateTo);
  }

  const where: Prisma.WarehouseDocumentItemWhereInput = {
    productId,
    document: documentWhere,
  };

  const [items, total] = await Promise.all([
    prisma.warehouseDocumentItem.findMany({
      where,
      skip,
      take: limit,
      orderBy: { document: { date: 'desc' } },
      include: {
        barcode: true,
        document: {
          select: {
            id: true,
            number: true,
            type: true,
            status: true,
            date: true,
            description: true,
            orderId: true,
            isAutoGenerated: true,
          },
        },
      },
    }),
    prisma.warehouseDocumentItem.count({ where }),
  ]);

  const data = items.map((item) => {
    const quantity = Number(item.quantity);
    const direction = getDocumentDirection(item.document.type);
    const stockDelta = item.document.status === 'CONFIRMED' ? quantity * direction : 0;

    return {
      id: item.id,
      document: item.document,
      barcode: item.barcode,
      quantity,
      stockDelta,
      unitPrice: item.unitPrice,
      scannedEan: item.scannedEan,
      baseQuantity: item.baseQuantity,
      quantityMultiplier: item.quantityMultiplier,
      notes: item.notes,
    };
  });

  return {
    product,
    data,
    total,
    page,
    limit,
    totalPages: Math.ceil(total / limit),
  };
}

export async function getStockDiscrepancies(query: StockDiscrepanciesQuery = {}) {
  const tenantId = requireTenantId();
  const products = await prisma.warehouseProduct.findMany({
    where: { tenantId },
    include: {
      catalog: true,
      items: {
        where: { document: { status: 'CONFIRMED' } },
        include: { document: { select: { type: true } } },
      },
    },
    orderBy: { name: 'asc' },
  });

  const data = products
    .map((product) => {
      const calculatedStock = product.items.reduce((stock, item) => {
        return stock + Number(item.quantity) * getDocumentDirection(item.document.type);
      }, 0);
      const currentStock = Number(product.currentStock);
      const difference = currentStock - calculatedStock;

      return {
        product: {
          id: product.id,
          sku: product.sku,
          name: product.name,
          unit: product.unit,
          catalog: product.catalog,
        },
        currentStock,
        calculatedStock,
        difference,
      };
    })
    .filter((entry) => query.includeZero === true || entry.difference !== 0);

  return { data, total: data.length };
}

function getDocumentDirection(type: string) {
  if (['PZ', 'PW'].includes(type)) return 1;
  if (['WZ', 'RW'].includes(type)) return -1;
  return 0;
}
