import { Prisma } from '@prisma/client';
import prisma from '../../lib/prisma';
import { getTenantId } from '../../lib/tenant-context';
import { addStockSyncJob } from '../queue/stock-sync.queue';

type StockSyncStatus = 'PENDING' | 'PROCESSING' | 'SUCCESS' | 'FAILED';
type DocumentType = 'PZ' | 'PW' | 'WZ' | 'RW';

export interface StockSyncLogsQuery {
  page?: number;
  limit?: number;
  shopId?: string;
  warehouseProductId?: string;
  status?: StockSyncStatus;
  dateFrom?: string;
  dateTo?: string;
}

export interface ProductMovementsQuery {
  page?: number;
  limit?: number;
  status?: 'DRAFT' | 'CONFIRMED' | 'CANCELLED';
  type?: DocumentType;
  dateFrom?: string;
  dateTo?: string;
}

export interface StockDiscrepanciesQuery {
  includeZero?: boolean;
}

export interface WarehouseDashboardQuery {
  lowStockThreshold?: number;
  limit?: number;
  failedSinceDays?: number;
}

function requireTenantId() {
  const tenantId = getTenantId();
  if (!tenantId) throw new Error('Brak kontekstu tenanta');
  return tenantId;
}

export async function getStockSyncLogs(query: StockSyncLogsQuery = {}) {
  const tenantId = requireTenantId();
  const { page = 1, limit = 50, shopId, warehouseProductId, status, dateFrom, dateTo } = query;
  const skip = (page - 1) * limit;

  const where: Prisma.StockSyncLogWhereInput = { tenantId };
  if (shopId) where.shopId = shopId;
  if (warehouseProductId) where.warehouseProductId = warehouseProductId;
  if (status) where.status = status;
  if (dateFrom || dateTo) {
    where.createdAt = {};
    if (dateFrom) where.createdAt.gte = new Date(dateFrom);
    if (dateTo) where.createdAt.lte = new Date(dateTo);
  }

  const [data, total] = await Promise.all([
    prisma.stockSyncLog.findMany({
      where,
      skip,
      take: limit,
      orderBy: { createdAt: 'desc' },
      include: {
        warehouseProduct: { select: { id: true, sku: true, name: true, currentStock: true } },
        shop: { select: { id: true, name: true, platform: true, status: true } },
        document: { select: { id: true, number: true, type: true, status: true, date: true } },
      },
    }),
    prisma.stockSyncLog.count({ where }),
  ]);

  return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
}

export async function retryStockSyncLog(id: string) {
  const tenantId = requireTenantId();
  const log = await prisma.stockSyncLog.findFirst({
    where: { id, tenantId },
    include: { warehouseProduct: true, shop: true },
  });

  if (!log) throw new Error('Log synchronizacji stanu nie znaleziony');

  const mapping = await prisma.shopProductMapping.findFirst({
    where: {
      tenantId,
      shopId: log.shopId,
      warehouseProductId: log.warehouseProductId,
      isActive: true,
      shop: { status: 'ACTIVE' },
    },
  });

  if (!mapping) {
    throw new Error('Brak aktywnego mapowania produktu do sklepu dla ponowienia synchronizacji');
  }

  const retryLog = await prisma.stockSyncLog.create({
    data: {
      tenantId,
      warehouseProductId: log.warehouseProductId,
      shopId: log.shopId,
      triggeredBy: 'MANUAL',
      documentId: log.documentId,
      stockBefore: log.stockAfter,
      stockAfter: log.warehouseProduct.currentStock,
      status: 'PENDING',
    },
  });

  await addStockSyncJob({
    logId: retryLog.id,
    tenantId,
    warehouseProductId: log.warehouseProductId,
    shopId: log.shopId,
    externalProductId: mapping.externalProductId,
    triggeredBy: 'MANUAL',
    documentId: log.documentId ?? undefined,
  });

  return retryLog;
}

export async function getProductMovements(productId: string, query: ProductMovementsQuery = {}) {
  const tenantId = requireTenantId();
  const product = await prisma.warehouseProduct.findFirst({
    where: { id: productId, tenantId },
    include: { catalog: true },
  });
  if (!product) throw new Error('Produkt nie znaleziony');

  const { page = 1, limit = 50, status, type, dateFrom, dateTo } = query;
  const skip = (page - 1) * limit;

  const documentWhere: Prisma.WarehouseDocumentWhereInput = { tenantId };
  if (status) documentWhere.status = status;
  if (type) documentWhere.type = type;
  if (dateFrom || dateTo) {
    documentWhere.date = {};
    if (dateFrom) documentWhere.date.gte = new Date(dateFrom);
    if (dateTo) documentWhere.date.lte = new Date(dateTo);
  }

  const where: Prisma.WarehouseDocumentItemWhereInput = {
    productId,
    document: documentWhere,
  };

  const [items, total] = await Promise.all([
    prisma.warehouseDocumentItem.findMany({
      where,
      skip,
      take: limit,
      orderBy: { document: { date: 'desc' } },
      include: {
        barcode: true,
        document: {
          select: {
            id: true,
            number: true,
            type: true,
            status: true,
            date: true,
            description: true,
            orderId: true,
            isAutoGenerated: true,
          },
        },
      },
    }),
    prisma.warehouseDocumentItem.count({ where }),
  ]);

  const data = items.map((item) => {
    const quantity = Number(item.quantity);
    const direction = getDocumentDirection(item.document.type);
    const stockDelta = item.document.status === 'CONFIRMED' ? quantity * direction : 0;

    return {
      id: item.id,
      document: item.document,
      barcode: item.barcode,
      quantity,
      stockDelta,
      unitPrice: item.unitPrice,
      scannedEan: item.scannedEan,
      baseQuantity: item.baseQuantity,
      quantityMultiplier: item.quantityMultiplier,
      notes: item.notes,
    };
  });

  return {
    product,
    data,
    total,
    page,
    limit,
    totalPages: Math.ceil(total / limit),
  };
}

export async function getWarehouseDashboard(query: WarehouseDashboardQuery = {}) {
  const tenantId = requireTenantId();
  const lowStockThreshold = normalizeLowStockThreshold(query.lowStockThreshold);
  const limit = normalizeDashboardLimit(query.limit);
  const failedSinceDays = normalizeFailedSinceDays(query.failedSinceDays);
  const failedSince = new Date(Date.now() - failedSinceDays * 24 * 60 * 60 * 1000);

  const productBaseWhere: Prisma.WarehouseProductWhereInput = { tenantId, isActive: true };
  const lowStockWhere: Prisma.WarehouseProductWhereInput = {
    ...productBaseWhere,
    currentStock: { lt: lowStockThreshold },
  };
  const negativeStockWhere: Prisma.WarehouseProductWhereInput = {
    ...productBaseWhere,
    currentStock: { lt: 0 },
  };
  const withoutBarcodeWhere: Prisma.WarehouseProductWhereInput = {
    ...productBaseWhere,
    barcodes: { none: { isActive: true } },
  };
  const withoutShopMappingWhere: Prisma.WarehouseProductWhereInput = {
    ...productBaseWhere,
    shopProductMappings: { none: { isActive: true } },
  };
  const withoutWholesaleOfferWhere: Prisma.WarehouseProductWhereInput = {
    ...productBaseWhere,
    wholesaleMappings: { none: { isActive: true } },
  };
  const failedStockSyncWhere: Prisma.StockSyncLogWhereInput = {
    tenantId,
    status: 'FAILED',
    createdAt: { gte: failedSince },
  };
  const failedWholesaleSyncWhere: Prisma.WholesaleSyncLogWhereInput = {
    tenantId,
    status: 'FAILED',
    startedAt: { gte: failedSince },
  };

  const [
    totalProducts,
    activeProducts,
    inactiveProducts,
    lowStockProductsCount,
    negativeStockProductsCount,
    productsWithoutBarcodeCount,
    productsWithoutShopMappingCount,
    productsWithoutWholesaleOfferCount,
    failedStockSyncLogsCount,
    failedWholesaleSyncLogsCount,
    draftDocumentsCount,
    lowStockProducts,
    negativeStockProducts,
    productsWithoutBarcode,
    productsWithoutShopMapping,
    productsWithoutWholesaleOffer,
    failedStockSyncLogs,
    failedWholesaleSyncLogs,
  ] = await Promise.all([
    prisma.warehouseProduct.count({ where: { tenantId } }),
    prisma.warehouseProduct.count({ where: productBaseWhere }),
    prisma.warehouseProduct.count({ where: { tenantId, isActive: false } }),
    prisma.warehouseProduct.count({ where: lowStockWhere }),
    prisma.warehouseProduct.count({ where: negativeStockWhere }),
    prisma.warehouseProduct.count({ where: withoutBarcodeWhere }),
    prisma.warehouseProduct.count({ where: withoutShopMappingWhere }),
    prisma.warehouseProduct.count({ where: withoutWholesaleOfferWhere }),
    prisma.stockSyncLog.count({ where: failedStockSyncWhere }),
    prisma.wholesaleSyncLog.count({ where: failedWholesaleSyncWhere }),
    prisma.warehouseDocument.count({ where: { tenantId, status: 'DRAFT' } }),
    prisma.warehouseProduct.findMany({
      where: lowStockWhere,
      take: limit,
      orderBy: [{ currentStock: 'asc' }, { name: 'asc' }],
      include: { catalog: true },
    }),
    prisma.warehouseProduct.findMany({
      where: negativeStockWhere,
      take: limit,
      orderBy: [{ currentStock: 'asc' }, { name: 'asc' }],
      include: { catalog: true },
    }),
    prisma.warehouseProduct.findMany({
      where: withoutBarcodeWhere,
      take: limit,
      orderBy: { name: 'asc' },
      include: { catalog: true },
    }),
    prisma.warehouseProduct.findMany({
      where: withoutShopMappingWhere,
      take: limit,
      orderBy: { name: 'asc' },
      include: { catalog: true },
    }),
    prisma.warehouseProduct.findMany({
      where: withoutWholesaleOfferWhere,
      take: limit,
      orderBy: { name: 'asc' },
      include: { catalog: true },
    }),
    prisma.stockSyncLog.findMany({
      where: failedStockSyncWhere,
      take: limit,
      orderBy: { createdAt: 'desc' },
      include: {
        warehouseProduct: { select: { id: true, sku: true, name: true, currentStock: true } },
        shop: { select: { id: true, name: true, platform: true } },
      },
    }),
    prisma.wholesaleSyncLog.findMany({
      where: failedWholesaleSyncWhere,
      take: limit,
      orderBy: { startedAt: 'desc' },
      include: {
        provider: { select: { id: true, name: true, platform: true, syncEnabled: true, isActive: true } },
      },
    }),
  ]);

  return {
    summary: {
      totalProducts,
      activeProducts,
      inactiveProducts,
      lowStockProducts: lowStockProductsCount,
      negativeStockProducts: negativeStockProductsCount,
      productsWithoutBarcode: productsWithoutBarcodeCount,
      productsWithoutShopMapping: productsWithoutShopMappingCount,
      productsWithoutWholesaleOffer: productsWithoutWholesaleOfferCount,
      failedStockSyncLogs: failedStockSyncLogsCount,
      failedWholesaleSyncLogs: failedWholesaleSyncLogsCount,
      draftDocuments: draftDocumentsCount,
    },
    thresholds: {
      lowStockThreshold,
      failedSinceDays,
      limit,
    },
    sections: {
      lowStockProducts,
      negativeStockProducts,
      productsWithoutBarcode,
      productsWithoutShopMapping,
      productsWithoutWholesaleOffer,
      failedStockSyncLogs,
      failedWholesaleSyncLogs,
    },
  };
}

export async function getStockDiscrepancies(query: StockDiscrepanciesQuery = {}) {
  const tenantId = requireTenantId();
  const products = await prisma.warehouseProduct.findMany({
    where: { tenantId },
    include: {
      catalog: true,
      items: {
        where: { document: { status: 'CONFIRMED' } },
        include: { document: { select: { type: true } } },
      },
    },
    orderBy: { name: 'asc' },
  });

  const data = products
    .map((product) => {
      const calculatedStock = product.items.reduce((stock, item) => {
        return stock + Number(item.quantity) * getDocumentDirection(item.document.type);
      }, 0);
      const currentStock = Number(product.currentStock);
      const difference = currentStock - calculatedStock;

      return {
        product: {
          id: product.id,
          sku: product.sku,
          name: product.name,
          unit: product.unit,
          catalog: product.catalog,
        },
        currentStock,
        calculatedStock,
        difference,
      };
    })
    .filter((entry) => query.includeZero === true || entry.difference !== 0);

  return { data, total: data.length };
}

function normalizeLowStockThreshold(value?: number) {
  if (value === undefined) return 1;
  if (!Number.isFinite(value)) throw new Error('lowStockThreshold musi być liczbą');
  return value;
}

function normalizeDashboardLimit(value?: number) {
  if (value === undefined) return 10;
  if (!Number.isInteger(value) || value < 1 || value > 50) {
    throw new Error('limit dashboardu musi być liczbą całkowitą od 1 do 50');
  }
  return value;
}

function normalizeFailedSinceDays(value?: number) {
  if (value === undefined) return 7;
  if (!Number.isInteger(value) || value < 1 || value > 90) {
    throw new Error('failedSinceDays musi być liczbą całkowitą od 1 do 90');
  }
  return value;
}

function getDocumentDirection(type: string) {
  if (['PZ', 'PW'].includes(type)) return 1;
  if (['WZ', 'RW'].includes(type)) return -1;
  return 0;
}
