import prisma from '../../lib/prisma';
import { Prisma } from '@prisma/client';
import { getTenantContext, getTenantId } from '../../lib/tenant-context';
import { syncStockForProducts } from '../stock/stock-sync.service';
import { consumeDocumentReservations, releaseDocumentReservations, reserveOrder } from './warehouse-reservations.service';
import { buildShippingInfoDescription, extractOrderShippingInfo } from '../orders/order-shipping-info.service';
import { STOCK_RESERVATION_ORDER_OPERATIONAL_STATUSES } from '../../lib/order-statuses';
import {
  buildWholesaleOrderCsvContent,
  detectWholesaleOrderCsvTemplate,
  providerPresetFromConfig,
  type WholesaleOrderCsvSourceRow,
} from './wholesale/order-csv-template';

// ─── Documents ───────────────────────────────────────────────────────────────

export type DocumentType = 'PZ' | 'ZH' | 'PW' | 'WZ' | 'ZW' | 'RW' | 'INW';
const STOCK_INCOMING_TYPES: DocumentType[] = ['PZ', 'PW', 'ZW'];
const STOCK_OUTGOING_TYPES: DocumentType[] = ['WZ', 'RW'];

export interface DocumentItemInput {
  productId: string;
  quantity?: number;
  /** Wymagany tylko dla INW: snapshot stanu systemowego z momentu wpisania pozycji. Jeśli null, serwis bierze bieżący `currentStock`. */
  systemQuantity?: number | null;
  barcodeId?: string;
  scannedEan?: string;
  baseQuantity?: number;
  quantityMultiplier?: number;
  unitPrice?: number;
  notes?: string;
  reservationId?: string | null;
}

export interface CreateDocumentInput {
  type: DocumentType;
  date?: string;
  description?: string;
  orderId?: string;
  isAutoGenerated?: boolean;
  metadataJson?: Prisma.InputJsonValue;
  items: DocumentItemInput[];
}

export interface UpdateDocumentInput {
  date?: string;
  description?: string;
  orderId?: string | null;
  items?: DocumentItemInput[];
}

export interface UpdateDocumentItemInput {
  quantity?: number;
  /** Tylko INW: aktualizacja snapshotu stanu systemowego (np. po wyborze "odśwież snapshot"). */
  systemQuantity?: number | null;
  baseQuantity?: number | null;
  quantityMultiplier?: number | null;
  unitPrice?: number | null;
  notes?: string | null;
}

export interface CancelDocumentInput {
  reason?: string;
}

export interface CreateFullInventoryDocumentInput {
  date?: string;
  description?: string;
}

export interface BulkUpsertInventoryItemsInput {
  items: DocumentItemInput[];
}

export interface CreateWzForOrderResult {
  document: Awaited<ReturnType<typeof getDocumentById>>;
  created: boolean;
  /** True gdy dokument zostal zatwierdzony w tym wywolaniu (nowy albo istniejacy roboczy). */
  confirmed?: boolean;
  skippedReason?: string;
}

/** Skan z pakowania: EAN zeskanowany dla konkretnej pozycji zamowienia. */
export interface OrderPackingScanInput {
  orderItemId?: string | null;
  productId?: string | null;
  scannedEan: string;
}

export interface CreateWzForOrderInput {
  saveAsDraft?: boolean;
  forceConfirm?: boolean;
  scans?: OrderPackingScanInput[];
  /** Wewnetrzne: ponowna proba po konflikcie unikalnosci — bez kolejnego retry. */
  retryAfterConflict?: boolean;
}

export interface CreateZhForOrderResult {
  documents: Array<NonNullable<Awaited<ReturnType<typeof getDocumentById>>>>;
  createdCount: number;
  skippedReason?: string;
}

export interface CreatePzFromWholesaleOrderResult {
  document: Awaited<ReturnType<typeof getDocumentById>>;
  created: boolean;
  skippedReason?: string;
}

export interface CreatePzFromWholesaleOrderInput {
  items?: DocumentItemInput[];
  saveAsDraft?: boolean;
}

export interface WholesaleOrderCsvExportResult {
  providerId: string | null;
  providerName: string | null;
  filename: string;
  content: string;
  mimeType: string;
  rows: number;
  confirmedDocuments: number;
  document?: Awaited<ReturnType<typeof getDocumentById>>;
  documents?: Array<NonNullable<Awaited<ReturnType<typeof getDocumentById>>>>;
}

export interface DocumentsQuery {
  page?: number;
  limit?: number;
  search?: string;
  type?: DocumentType;
  status?: 'DRAFT' | 'CONFIRMED' | 'CANCELLED';
  dateFrom?: string;
  dateTo?: string;
  isAutoGenerated?: boolean | string;
  stockWarning?: boolean | string;
}

interface PreparedDocumentItem {
  productId: string;
  quantity: number;
  systemQuantity?: number | null;
  barcodeId?: string;
  scannedEan?: string;
  baseQuantity?: number;
  quantityMultiplier?: number;
  unitPrice?: number;
  notes?: string;
  reservationId?: string | null;
}

const FULL_INVENTORY_SCOPE = 'ALL_ACTIVE_PRODUCTS';

const documentDetailInclude = {
  items: {
    include: {
      product: {
        include: {
          wholesaleMappings: {
            where: {
              isActive: true,
              provider: { isActive: true },
            },
            include: {
              provider: {
                select: {
                  id: true,
                  name: true,
                  configJson: true,
                },
              },
            },
            orderBy: [{ lastSyncAt: 'desc' }, { updatedAt: 'desc' }],
            take: 10,
          },
        },
      },
      barcode: true,
      reservation: true,
    },
  },
  order: true,
} satisfies Prisma.WarehouseDocumentInclude;

function normalizeBooleanQuery(value: boolean | string | undefined) {
  if (value === undefined) return undefined;
  if (value === true || value === 'true') return true;
  if (value === false || value === 'false') return false;
  return undefined;
}

function parseDateInput(value: string) {
  const trimmed = value.trim();
  const dateOnlyMatch = /^(\d{4})-(\d{2})-(\d{2})$/.exec(trimmed);
  if (dateOnlyMatch) {
    const [, year, month, day] = dateOnlyMatch;
    return new Date(Number(year), Number(month) - 1, Number(day));
  }
  return new Date(trimmed);
}

function startOfDay(value: string) {
  const date = parseDateInput(value);
  date.setHours(0, 0, 0, 0);
  return date;
}

function endOfDay(value: string) {
  const date = parseDateInput(value);
  date.setHours(23, 59, 59, 999);
  return date;
}

async function withAuditUsers<T extends {
  createdByUserId?: string | null;
  confirmedByUserId?: string | null;
  cancelledByUserId?: string | null;
} | null>(document: T) {
  if (!document) return document;

  const userIds = Array.from(new Set([
    document.createdByUserId,
    document.confirmedByUserId,
    document.cancelledByUserId,
  ].filter((id): id is string => Boolean(id))));

  if (userIds.length === 0) {
    return {
      ...document,
      createdByUser: null,
      confirmedByUser: null,
      cancelledByUser: null,
    };
  }

  const users = await prisma.user.findMany({
    where: { id: { in: userIds } },
    select: { id: true, name: true, email: true },
  });
  const userById = new Map(users.map((user) => [user.id, user]));

  return {
    ...document,
    createdByUser: document.createdByUserId ? userById.get(document.createdByUserId) ?? null : null,
    confirmedByUser: document.confirmedByUserId ? userById.get(document.confirmedByUserId) ?? null : null,
    cancelledByUser: document.cancelledByUserId ? userById.get(document.cancelledByUserId) ?? null : null,
  };
}

export async function getDocuments(query: DocumentsQuery = {}) {
  const tenantId = getTenantId();
  const { page = 1, limit = 20, search, type, status, dateFrom, dateTo } = query;
  const skip = (page - 1) * limit;
  const isAutoGenerated = normalizeBooleanQuery(query.isAutoGenerated);
  const stockWarning = normalizeBooleanQuery(query.stockWarning);
  const searchTerm = search?.trim();

  const where: any = {};
  if (tenantId) where.tenantId = tenantId;
  if (searchTerm) {
    where.OR = [
      { number: { contains: searchTerm, mode: 'insensitive' } },
      { description: { contains: searchTerm, mode: 'insensitive' } },
      { order: { is: { orderReference: { contains: searchTerm, mode: 'insensitive' } } } },
      { order: { is: { externalOrderId: { contains: searchTerm, mode: 'insensitive' } } } },
    ];
  }
  if (type) where.type = type;
  if (status) where.status = status;
  if (isAutoGenerated !== undefined) where.isAutoGenerated = isAutoGenerated;
  if (stockWarning !== undefined) where.metadataJson = { path: ['stockWarning'], equals: stockWarning };
  if (dateFrom || dateTo) {
    where.date = {};
    if (dateFrom) where.date.gte = startOfDay(dateFrom);
    if (dateTo) where.date.lte = endOfDay(dateTo);
  }

  const monthStart = new Date();
  monthStart.setDate(1);
  monthStart.setHours(0, 0, 0, 0);
  const monthEnd = new Date(monthStart);
  monthEnd.setMonth(monthEnd.getMonth() + 1);
  monthEnd.setMilliseconds(-1);
  const tenantWhere = tenantId ? { tenantId } : {};

  const [documents, total, stockWarningCount, confirmedThisMonth, autoWzFromOrders] = await Promise.all([
    prisma.warehouseDocument.findMany({
      where,
      skip,
      take: limit,
      orderBy: [{ date: 'desc' }, { createdAt: 'desc' }],
      select: {
        id: true,
        tenantId: true,
        number: true,
        type: true,
        status: true,
        date: true,
        description: true,
        orderId: true,
        createdByUserId: true,
        confirmedAt: true,
        confirmedByUserId: true,
        cancelledAt: true,
        cancelledByUserId: true,
        cancelReason: true,
        isAutoGenerated: true,
        metadataJson: true,
        createdAt: true,
        updatedAt: true,
        order: { select: { id: true, orderReference: true, externalOrderId: true } },
        _count: { select: { items: true } },
      },
    }),
    prisma.warehouseDocument.count({ where }),
    prisma.warehouseDocument.count({
      where: {
        ...tenantWhere,
        metadataJson: { path: ['stockWarning'], equals: true },
      } as any,
    }),
    prisma.warehouseDocument.count({
      where: {
        ...tenantWhere,
        status: 'CONFIRMED',
        date: { gte: monthStart, lte: monthEnd },
      },
    }),
    prisma.warehouseDocument.count({
      where: {
        ...tenantWhere,
        type: 'WZ',
        isAutoGenerated: true,
        orderId: { not: null },
      },
    }),
  ]);
  const documentIds = documents.map((document) => document.id);
  const relatedPzIds = documents
    .map((document) => document.type === 'ZH' && document.metadataJson && typeof document.metadataJson === 'object' && !Array.isArray(document.metadataJson)
      ? (document.metadataJson as Record<string, unknown>).convertedToPzDocumentId
      : null)
    .filter((id): id is string => typeof id === 'string');
  const relatedPzDocuments = relatedPzIds.length === 0
    ? []
    : await prisma.warehouseDocument.findMany({
        where: { id: { in: relatedPzIds }, type: 'PZ' },
        select: { id: true, number: true, status: true },
      });
  const relatedPzById = new Map(relatedPzDocuments.map((document) => [document.id, document]));
  const [quantityGroups, valueGroups] = documentIds.length === 0
    ? [[], []] as const
    : await Promise.all([
      prisma.warehouseDocumentItem.groupBy({
        by: ['documentId'],
        where: { documentId: { in: documentIds } },
        _sum: { quantity: true },
      }),
      prisma.$queryRaw<Array<{ documentId: string; totalValue: Prisma.Decimal | number | string | null }>>`
        SELECT document_id AS "documentId",
               COALESCE(SUM(quantity * COALESCE(unit_price, 0)), 0) AS "totalValue"
        FROM warehouse_document_items
        WHERE document_id IN (${Prisma.join(documentIds)})
        GROUP BY document_id
      `,
    ]);
  const quantityByDocumentId = new Map(quantityGroups.map((row) => [row.documentId, Number(row._sum.quantity ?? 0)]));
  const valueByDocumentId = new Map(valueGroups.map((row) => [row.documentId, Number(row.totalValue ?? 0)]));
  const data = documents.map((document) => ({
    ...document,
    relatedPz: document.type === 'ZH' && document.metadataJson && typeof document.metadataJson === 'object' && !Array.isArray(document.metadataJson)
      ? relatedPzById.get(String((document.metadataJson as Record<string, unknown>).convertedToPzDocumentId)) ?? null
      : null,
    itemsCount: document._count.items,
    totalQuantity: quantityByDocumentId.get(document.id) ?? 0,
    totalValue: valueByDocumentId.get(document.id) ?? 0,
  }));

  return {
    data,
    total,
    page,
    limit,
    totalPages: Math.ceil(total / limit),
    summary: {
      stockWarningCount,
      confirmedThisMonth,
      autoWzFromOrders,
    },
  };
}

export async function getDocumentById(id: string) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const document = await prisma.warehouseDocument.findFirst({
    where,
    include: documentDetailInclude,
  });

  return withAuditUsers(document);
}

export async function createDocument(input: CreateDocumentInput) {
  const tenantId = getTenantId();
  if (!tenantId) throw new Error('Brak kontekstu tenanta');

  const preparedItems = await prepareDocumentItems(tenantId, input.items, true, input.type);
  const context = getTenantContext();
  const documentDate = input.date ? parseDateInput(input.date) : new Date();

  return prisma.$transaction(async (tx) => {
    const number = await generateDocumentNumber(tx, tenantId, input.type, documentDate);

    return tx.warehouseDocument.create({
      data: {
        tenantId,
        number,
        type: input.type,
        status: 'DRAFT',
        date: documentDate,
        description: input.description,
        orderId: input.orderId,
        createdByUserId: context?.userId,
        isAutoGenerated: input.isAutoGenerated ?? false,
        metadataJson: input.metadataJson,
        items: {
          create: preparedItems.map((item) => ({
            productId: item.productId,
            quantity: item.quantity,
            systemQuantity: item.systemQuantity ?? null,
            barcodeId: item.barcodeId,
            scannedEan: item.scannedEan,
            baseQuantity: item.baseQuantity,
            quantityMultiplier: item.quantityMultiplier,
            unitPrice: item.unitPrice,
            notes: item.notes,
            reservationId: item.reservationId,
          })),
        },
      },
      include: documentDetailInclude,
    });
  });
}

export async function createFullInventoryDocument(input: CreateFullInventoryDocumentInput = {}) {
  const tenantId = getTenantId();
  if (!tenantId) throw new Error('Brak kontekstu tenanta');

  const context = getTenantContext();
  const documentDate = input.date ? parseDateInput(input.date) : new Date();
  const description = input.description?.trim() || 'Pełna inwentaryzacja magazynu';

  const document = await prisma.$transaction(async (tx) => {
    const number = await generateDocumentNumber(tx, tenantId, 'INW', documentDate);

    return tx.warehouseDocument.create({
      data: {
        tenantId,
        number,
        type: 'INW',
        status: 'DRAFT',
        date: documentDate,
        description,
        createdByUserId: context?.userId,
        metadataJson: {
          inventoryScope: FULL_INVENTORY_SCOPE,
          source: 'FULL_INVENTORY_SESSION',
          startedAt: new Date().toISOString(),
        },
      },
      include: documentDetailInclude,
    });
  });

  return withAuditUsers(document);
}

function metadataRecord(value: Prisma.JsonValue | null | undefined) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
  return value as Record<string, unknown>;
}

function numericQuantity(value: unknown) {
  const number = Number(value ?? 0);
  return Number.isFinite(number) ? number : 0;
}

function addQuantity(map: Map<string, number>, productId: string, quantity: unknown) {
  map.set(productId, (map.get(productId) ?? 0) + numericQuantity(quantity));
}

function formatDocumentQuantity(value: number) {
  return new Intl.NumberFormat('pl-PL', { maximumFractionDigits: 3 }).format(value);
}

function metadataString(value: Prisma.JsonValue | null | undefined, key: string) {
  const record = metadataRecord(value);
  const item = record[key];
  return typeof item === 'string' && item.trim() ? item.trim() : null;
}

function numberFromDecimal(value: Prisma.Decimal | number | string | null | undefined) {
  if (value === null || value === undefined) return 0;
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : 0;
}

function slugify(value: string) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'dostawca';
}

function todayFileDate() {
  return new Date().toISOString().slice(0, 10);
}

function pickWholesaleMappingForProvider(item: any, providerId: string | null) {
  const mappings = Array.isArray(item.product?.wholesaleMappings)
    ? item.product.wholesaleMappings
    : [];
  if (mappings.length === 0) return null;
  if (!providerId) return mappings[0];
  return mappings.find((mapping: any) => mapping.providerId === providerId) ?? mappings[0];
}

function buildWholesaleOrderCsv(documents: any[]): Omit<WholesaleOrderCsvExportResult, 'confirmedDocuments' | 'document' | 'documents'> {
  const firstDocument = documents[0];
  const firstMetadata = firstDocument ? firstDocument.metadataJson as Prisma.JsonValue | null : null;
  const providerId = metadataString(firstMetadata, 'providerId');
  let providerName = metadataString(firstMetadata, 'providerName');
  const rows: WholesaleOrderCsvSourceRow[] = [];

  for (const document of documents) {
    const documentProviderId = metadataString(document.metadataJson as Prisma.JsonValue | null, 'providerId') ?? providerId;
    const documentProviderName = metadataString(document.metadataJson as Prisma.JsonValue | null, 'providerName');
    if (!providerName && documentProviderName) providerName = documentProviderName;

    for (const item of document.items ?? []) {
      const mapping = pickWholesaleMappingForProvider(item, documentProviderId);
      const mappingProviderName = typeof mapping?.provider?.name === 'string' ? mapping.provider.name : null;
      if (!providerName && mappingProviderName) providerName = mappingProviderName;

      const code = [
        mapping?.externalSku,
        mapping?.externalEan,
        item.scannedEan,
        item.product?.sku,
      ].find((value) => typeof value === 'string' && value.trim())?.trim();
      if (!code) continue;

      rows.push({
        code,
        quantity: numberFromDecimal(item.quantity),
        unit: item.product?.unit ?? 'szt',
        providerPreset: providerPresetFromConfig(mapping?.provider?.configJson as Prisma.JsonValue | null | undefined),
      });
    }
  }

  if (rows.length === 0) throw new Error('Brak pozycji z kodem dostawcy do eksportu CSV');

  const template = detectWholesaleOrderCsvTemplate(providerName, rows.map((row) => row.providerPreset ?? null));
  const csv = buildWholesaleOrderCsvContent(template, rows);
  const documentPart = documents.length === 1 ? `-${slugify(documents[0].number)}` : '';

  return {
    providerId,
    providerName,
    filename: `zamowienie-${slugify(providerName ?? 'dostawca')}${documentPart}-${todayFileDate()}.csv`,
    content: csv.content,
    mimeType: 'text/csv;charset=utf-8',
    rows: csv.rows,
  };
}

export async function exportWholesaleOrderCsv(id: string): Promise<WholesaleOrderCsvExportResult> {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const document = await prisma.warehouseDocument.findFirst({
    where,
    include: documentDetailInclude,
  });
  if (!document) throw new Error('Dokument nie znaleziony');
  if (document.type !== 'ZH') throw new Error('CSV zamówienia można wygenerować tylko dla dokumentu ZH');
  if (document.status === 'CANCELLED') throw new Error('Nie można wygenerować CSV z anulowanego zamówienia hurtowego');
  if (document.items.length === 0) throw new Error('Dokument ZH nie ma żadnych pozycji');

  const csv = buildWholesaleOrderCsv([document]);
  let confirmedDocuments = 0;
  if (document.status === 'DRAFT') {
    await confirmDocument(document.id);
    confirmedDocuments = 1;
  }

  return {
    ...csv,
    confirmedDocuments,
    document: await getDocumentById(document.id),
  };
}

export async function exportWholesaleOrdersForProviderCsv(providerId: string): Promise<WholesaleOrderCsvExportResult> {
  const tenantId = getTenantId();
  if (!tenantId) throw new Error('Brak kontekstu tenanta');

  const documents = await prisma.warehouseDocument.findMany({
    where: {
      tenantId,
      type: 'ZH',
      status: 'DRAFT',
    },
    include: documentDetailInclude,
    orderBy: [{ date: 'asc' }, { createdAt: 'asc' }],
  });
  const providerDocuments = documents.filter((document) => metadataString(document.metadataJson, 'providerId') === providerId);
  if (providerDocuments.length === 0) throw new Error('Brak roboczych dokumentów ZH do eksportu dla tego dostawcy');

  const csv = buildWholesaleOrderCsv(providerDocuments);
  const documentIds = providerDocuments.map((document) => document.id);
  for (const documentId of documentIds) {
    await confirmDocument(documentId);
  }

  const confirmedDocuments = (await Promise.all(documentIds.map((documentId) => getDocumentById(documentId))))
    .filter((document): document is NonNullable<typeof document> => Boolean(document));

  return {
    ...csv,
    confirmedDocuments: documentIds.length,
    documents: confirmedDocuments,
  };
}

export async function createPzFromWholesaleOrder(id: string, input: CreatePzFromWholesaleOrderInput = {}): Promise<CreatePzFromWholesaleOrderResult> {
  const tenantId = getTenantId();
  const context = getTenantContext();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const sourceDocument = await prisma.warehouseDocument.findFirst({
    where,
    include: documentDetailInclude,
  });
  if (!sourceDocument) throw new Error('Dokument nie znaleziony');
  if (sourceDocument.type !== 'ZH') throw new Error('PZ można utworzyć tylko z dokumentu ZH');
  if (sourceDocument.status === 'CANCELLED') throw new Error('Nie można utworzyć PZ z anulowanego zamówienia hurtowego');
  if (sourceDocument.items.length === 0) throw new Error('Dokument ZH nie ma żadnych pozycji');

  const sourceMetadata = metadataRecord(sourceDocument.metadataJson);
  const existingPzId = typeof sourceMetadata.convertedToPzDocumentId === 'string'
    ? sourceMetadata.convertedToPzDocumentId
    : null;
  if (existingPzId) {
    const existing = await getDocumentById(existingPzId);
    if (existing && existing.status !== 'CANCELLED') {
      if (sourceDocument.status === 'DRAFT') {
        await prisma.warehouseDocument.update({
          where: { id: sourceDocument.id },
          data: {
            status: 'CONFIRMED',
            confirmedAt: new Date(),
            confirmedByUserId: context?.userId,
          },
        });
      }

      return {
        document: existing,
        created: false,
        skippedReason: `PZ dla ${sourceDocument.number} już istnieje`,
      };
    }
  }

  const documentDate = new Date();
  const shouldConfirmPz = input.saveAsDraft !== true;
  const usesDeliveryCheckItems = Array.isArray(input.items);
  const sourceItemByProductId = new Map(sourceDocument.items.map((item) => [item.productId, item]));
  const sourceQuantityByProductId = new Map<string, number>();
  for (const item of sourceDocument.items) {
    addQuantity(sourceQuantityByProductId, item.productId, item.quantity);
  }

  const pzItems: PreparedDocumentItem[] = usesDeliveryCheckItems
    ? await prepareDocumentItems(sourceDocument.tenantId, input.items ?? [], true, 'PZ')
    : sourceDocument.items.map((item) => ({
        productId: item.productId,
        quantity: numericQuantity(item.quantity),
        unitPrice: item.unitPrice === null || item.unitPrice === undefined ? undefined : Number(item.unitPrice),
        notes: item.notes ?? `Przyjęcie z ${sourceDocument.number}`,
      }));

  if (pzItems.length === 0) {
    throw new Error(usesDeliveryCheckItems ? 'Brak zeskanowanych pozycji do utworzenia PZ' : 'Dokument ZH nie ma żadnych pozycji');
  }

  const acceptedQuantityByProductId = new Map<string, number>();
  for (const item of pzItems) {
    addQuantity(acceptedQuantityByProductId, item.productId, item.quantity);
  }

  const deliveryCheckSummary = usesDeliveryCheckItems
    ? {
        totalExpected: Array.from(sourceQuantityByProductId.values()).reduce((sum, quantity) => sum + quantity, 0),
        totalAccepted: Array.from(acceptedQuantityByProductId.values()).reduce((sum, quantity) => sum + quantity, 0),
        missingItems: Array.from(sourceQuantityByProductId.entries())
          .map(([productId, expected]) => {
            const accepted = acceptedQuantityByProductId.get(productId) ?? 0;
            return {
              productId,
              sku: sourceItemByProductId.get(productId)?.product?.sku,
              name: sourceItemByProductId.get(productId)?.product?.name,
              expected,
              accepted,
              missing: Math.max(0, expected - accepted),
            };
          })
          .filter((item) => item.missing > 0),
        overageItems: Array.from(acceptedQuantityByProductId.entries())
          .map(([productId, accepted]) => {
            const expected = sourceQuantityByProductId.get(productId) ?? 0;
            return {
              productId,
              sku: sourceItemByProductId.get(productId)?.product?.sku,
              name: sourceItemByProductId.get(productId)?.product?.name,
              expected,
              accepted,
              overage: Math.max(0, accepted - expected),
              outsideOrder: !sourceQuantityByProductId.has(productId),
            };
          })
          .filter((item) => item.overage > 0),
      }
    : undefined;

  const createdDocument = await prisma.$transaction(async (tx) => {
    const number = await generateDocumentNumber(tx, sourceDocument.tenantId, 'PZ', documentDate);
    const metadataJson = {
      source: 'WHOLESALE_ORDER',
      wholesaleOrderDocumentId: sourceDocument.id,
      wholesaleOrderNumber: sourceDocument.number,
      providerId: sourceMetadata.providerId,
      providerName: sourceMetadata.providerName,
      createdFromDeliveryCheck: usesDeliveryCheckItems,
      savedAsDraft: !shouldConfirmPz,
      deliveryCheckSummary,
    };

    const pz = await tx.warehouseDocument.create({
      data: {
        tenantId: sourceDocument.tenantId,
        number,
        type: 'PZ',
        status: shouldConfirmPz ? 'CONFIRMED' : 'DRAFT',
        date: documentDate,
        description: usesDeliveryCheckItems
          ? `PZ według kontroli dostawy ${sourceDocument.number}`
          : `PZ do zamówienia hurtowego ${sourceDocument.number}`,
        createdByUserId: context?.userId,
        confirmedAt: shouldConfirmPz ? new Date() : undefined,
        confirmedByUserId: shouldConfirmPz ? context?.userId : undefined,
        metadataJson: JSON.parse(JSON.stringify(metadataJson)),
        items: {
          create: pzItems.map((item) => {
            const sourceItem = sourceItemByProductId.get(item.productId);
            const expected = sourceQuantityByProductId.get(item.productId);
            const accepted = acceptedQuantityByProductId.get(item.productId) ?? numericQuantity(item.quantity);
            const deliveryCheckNote = usesDeliveryCheckItems && expected !== undefined && accepted < expected
              ? `Kontrola dostawy: przyjęto ${formatDocumentQuantity(accepted)} z ${formatDocumentQuantity(expected)}, brak ${formatDocumentQuantity(expected - accepted)}`
              : usesDeliveryCheckItems && expected !== undefined && accepted > expected
                ? `Kontrola dostawy: przyjęto ${formatDocumentQuantity(accepted)} z ${formatDocumentQuantity(expected)}, nadwyżka ${formatDocumentQuantity(accepted - expected)}`
                : usesDeliveryCheckItems && expected === undefined
                  ? `Kontrola dostawy: produkt poza ${sourceDocument.number}`
                  : undefined;
            return {
              productId: item.productId,
              quantity: item.quantity,
              barcodeId: item.barcodeId,
              scannedEan: item.scannedEan,
              baseQuantity: item.baseQuantity,
              quantityMultiplier: item.quantityMultiplier,
              unitPrice: item.unitPrice ?? sourceItem?.unitPrice ?? null,
              notes: item.notes ?? deliveryCheckNote ?? sourceItem?.notes ?? `Przyjęcie z ${sourceDocument.number}`,
            };
          }),
        },
      },
      include: documentDetailInclude,
    });

    if (shouldConfirmPz) {
      await applyIncomingPurchaseCosts(tx, 'PZ', pz.items);
      await applyStockDeltas(tx, 'PZ', pz.items);
    }

    await tx.warehouseDocument.update({
      where: { id: sourceDocument.id },
      data: {
        ...(sourceDocument.status === 'DRAFT'
          ? {
              status: 'CONFIRMED' as const,
              confirmedAt: new Date(),
              confirmedByUserId: context?.userId,
            }
          : {}),
        metadataJson: JSON.parse(JSON.stringify({
          ...sourceMetadata,
          convertedToPzDocumentId: pz.id,
          convertedToPzDocumentNumber: pz.number,
          convertedAt: new Date().toISOString(),
        })),
      },
    });

    return pz;
  });

  if (shouldConfirmPz) {
    const affectedProductIds = Array.from(new Set(createdDocument.items.map((item) => item.productId)));
    await reallocateWholesaleBackordersForProducts(sourceDocument.tenantId, affectedProductIds);
    await syncStockForProducts(affectedProductIds, 'DOCUMENT_CONFIRM', createdDocument.id);
  }

  return {
    document: await withAuditUsers(createdDocument),
    created: true,
  };
}

/**
 * DRAFT WZ to karta pakowania — pozycje musza odpowiadac biezacym ACTIVE rezerwacjom
 * LOCAL_STOCK zamowienia. Po realokacji (PZ zamienia backorder na rezerwacje lokalna
 * z nowym id) albo cyklu release→reserve stare pozycje wskazuja martwe rezerwacje.
 * Ta funkcja przebudowuje pozycje draftu, zachowujac skany EAN. Pozycje bez nastepcy
 * (rezerwacja zwolniona, brak nowej) zostaja — confirmDocument zdejmie ich stan
 * sciezka DETACH.
 */
export async function syncWzDraftItemsWithReservations(documentId: string) {
  const document = await prisma.warehouseDocument.findUnique({
    where: { id: documentId },
    include: {
      items: {
        include: { reservation: { select: { id: true, status: true, source: true, orderItemId: true } } },
      },
    },
  });
  if (!document || document.type !== 'WZ' || document.status !== 'DRAFT' || !document.orderId) return;

  const activeLocal = await prisma.warehouseReservation.findMany({
    where: {
      tenantId: document.tenantId,
      orderId: document.orderId,
      status: 'ACTIVE',
      source: 'LOCAL_STOCK',
    },
    orderBy: { createdAt: 'asc' },
  });
  const activeById = new Map(activeLocal.map((reservation) => [reservation.id, reservation]));

  const linkedIds = new Set<string>();
  for (const item of document.items) {
    if (item.reservationId && activeById.has(item.reservationId)) linkedIds.add(item.reservationId);
  }

  const removeItemIds: string[] = [];
  const quantityUpdates: Array<{ itemId: string; quantity: Prisma.Decimal }> = [];
  const eanByOrderItemId = new Map<string, string>();
  const eanByProductId = new Map<string, string>();

  for (const item of document.items) {
    if (!item.reservationId) continue; // reczna/nadmiarowa pozycja — zdejmie stan sama

    const current = activeById.get(item.reservationId);
    if (current) {
      if (!new Prisma.Decimal(item.quantity).equals(current.quantity)) {
        quantityUpdates.push({ itemId: item.id, quantity: new Prisma.Decimal(current.quantity) });
      }
      continue;
    }

    const reservation = item.reservation;
    if (reservation?.status === 'ACTIVE' && reservation.source === 'WHOLESALE_BACKORDER') {
      // Towaru nie ma na polce — pozycja wroci po dostawie jako rezerwacja lokalna.
      removeItemIds.push(item.id);
      continue;
    }
    if (reservation?.status === 'CONSUMED') continue; // wydana innym dokumentem — nie ruszamy

    const orderItemId = reservation?.orderItemId ?? null;
    const replaced = activeLocal.some((candidate) => !linkedIds.has(candidate.id)
      && (orderItemId ? candidate.orderItemId === orderItemId : candidate.warehouseProductId === item.productId));
    if (!replaced) continue; // brak nastepcy — DETACH przy zatwierdzeniu

    const scannedEan = item.scannedEan?.trim();
    if (scannedEan) {
      if (orderItemId && !eanByOrderItemId.has(orderItemId)) eanByOrderItemId.set(orderItemId, scannedEan);
      if (!eanByProductId.has(item.productId)) eanByProductId.set(item.productId, scannedEan);
    }
    removeItemIds.push(item.id);
  }

  const missingReservations = activeLocal.filter((reservation) => !linkedIds.has(reservation.id));
  if (removeItemIds.length === 0 && missingReservations.length === 0 && quantityUpdates.length === 0) return;

  await prisma.$transaction(async (tx) => {
    if (removeItemIds.length > 0) {
      await tx.warehouseDocumentItem.deleteMany({ where: { id: { in: removeItemIds } } });
    }
    for (const update of quantityUpdates) {
      await tx.warehouseDocumentItem.update({
        where: { id: update.itemId },
        data: { quantity: update.quantity },
      });
    }
    for (const reservation of missingReservations) {
      await tx.warehouseDocumentItem.create({
        data: {
          documentId,
          productId: reservation.warehouseProductId,
          quantity: reservation.quantity,
          reservationId: reservation.id,
          scannedEan: (reservation.orderItemId ? eanByOrderItemId.get(reservation.orderItemId) : undefined)
            ?? eanByProductId.get(reservation.warehouseProductId),
          notes: 'Synchronizacja pozycji z rezerwacjami',
        },
      });
    }
  });
}

/** Skany z pakowania trafiaja na pozycje WZ — to one decyduja, czy WZ mozna zamknac bez pytania o stan. */
async function applyPackingScansToDocument(documentId: string, scans: OrderPackingScanInput[]) {
  const normalized = scans
    .map((scan) => ({
      orderItemId: scan.orderItemId?.trim() || null,
      productId: scan.productId?.trim() || null,
      scannedEan: scan.scannedEan?.trim() || '',
    }))
    .filter((scan) => scan.scannedEan.length > 0);
  if (normalized.length === 0) return;

  const items = await prisma.warehouseDocumentItem.findMany({
    where: { documentId },
    select: { id: true, productId: true, scannedEan: true, reservation: { select: { orderItemId: true } } },
  });

  const byOrderItemId = new Map<string, string>();
  const byProductId = new Map<string, string>();
  for (const scan of normalized) {
    if (scan.orderItemId && !byOrderItemId.has(scan.orderItemId)) byOrderItemId.set(scan.orderItemId, scan.scannedEan);
    if (scan.productId && !byProductId.has(scan.productId)) byProductId.set(scan.productId, scan.scannedEan);
  }

  for (const item of items) {
    if (item.scannedEan?.trim()) continue;
    const orderItemId = item.reservation?.orderItemId ?? null;
    const scannedEan = (orderItemId ? byOrderItemId.get(orderItemId) : undefined) ?? byProductId.get(item.productId);
    if (!scannedEan) continue;

    await prisma.warehouseDocumentItem.update({
      where: { id: item.id },
      data: { scannedEan },
    });
  }
}

export async function createWzForOrder(orderId: string, input: CreateWzForOrderInput = {}): Promise<CreateWzForOrderResult> {
  const contextTenantId = getTenantId();
  const order = await prisma.order.findFirst({
    where: {
      id: orderId,
      ...(contextTenantId ? { shop: { tenantId: contextTenantId } } : {}),
    },
    include: {
      shop: true,
      items: true,
    },
  });

  if (!order) throw new Error('Zamówienie nie znalezione');

  const existingDocument = await prisma.warehouseDocument.findFirst({
    where: {
      tenantId: order.shop.tenantId,
      orderId,
      type: 'WZ',
      status: { not: 'CANCELLED' },
    },
    include: documentDetailInclude,
  });

  if (existingDocument) {
    // Roboczy WZ powstaje juz przy rezerwacji, wiec pakowanie musi umiec go domknac:
    // synchronizujemy pozycje z rezerwacjami, dopisujemy skany EAN i zatwierdzamy
    // zamiast odsylac "WZ juz istnieje".
    if (existingDocument.status === 'DRAFT') {
      await syncWzDraftItemsWithReservations(existingDocument.id);
      await applyPackingScansToDocument(existingDocument.id, input.scans ?? []);

      if (input.saveAsDraft !== true && (input.forceConfirm === true || (await getWarehouseSettings(order.shop.tenantId)).autoConfirmWzOnOrder)) {
        // Auto-confirm z ustawien (bez jawnej akcji uzytkownika) nie moze domykac
        // dokumentu oznaczonego ostrzezeniem stanu przy tworzeniu.
        const blockedByStockWarning = input.forceConfirm !== true
          && metadataRecord(existingDocument.metadataJson).autoConfirmBlockedByStockWarning === true;
        if (!blockedByStockWarning) {
          await confirmDocument(existingDocument.id);
          return {
            document: await getDocumentById(existingDocument.id),
            created: false,
            confirmed: true,
          };
        }
      }

      return {
        document: await getDocumentById(existingDocument.id),
        created: false,
        skippedReason: 'WZ dla tego zamówienia już istnieje — zapisano skany',
      };
    }

    return {
      document: await withAuditUsers(existingDocument),
      created: false,
      skippedReason: 'WZ dla tego zamówienia już istnieje',
    };
  }

  if (order.items.length === 0) {
    return { document: null, created: false, skippedReason: 'Zamówienie nie ma pozycji' };
  }

  // WZ wydaje tylko towar z polki: rezerwacje hurtowe (backorder) nie maja fizycznie
  // sztuk, wiec nie wchodza na dokument — wejda po PZ, gdy realokacja zamieni je na lokalne.
  const activeLocalReservationsWhere = {
    tenantId: order.shop.tenantId,
    orderId: order.id,
    status: 'ACTIVE' as const,
    source: 'LOCAL_STOCK' as const,
  };

  let activeReservations = await prisma.warehouseReservation.findMany({
    where: activeLocalReservationsWhere,
    include: {
      warehouseProduct: true,
      orderItem: true,
    },
    orderBy: { createdAt: 'asc' },
  });

  let reservationResult: Awaited<ReturnType<typeof reserveOrder>> | null = null;
  if (activeReservations.length === 0) {
    reservationResult = await reserveOrder(order.id);
    activeReservations = await prisma.warehouseReservation.findMany({
      where: activeLocalReservationsWhere,
      include: {
        warehouseProduct: true,
        orderItem: true,
      },
      orderBy: { createdAt: 'asc' },
    });
  }

  if (activeReservations.length === 0) {
    const hasBackorder = await prisma.warehouseReservation.count({
      where: { tenantId: order.shop.tenantId, orderId: order.id, status: 'ACTIVE', source: 'WHOLESALE_BACKORDER' },
    });
    return {
      document: null,
      created: false,
      skippedReason: hasBackorder > 0
        ? 'Brak pozycji lokalnych do wydania — wszystko czeka na domówienie z hurtowni'
        : 'Brak aktywnych rezerwacji do wydania WZ',
    };
  }

  const stockWarning = Boolean(
    reservationResult && (reservationResult.partial > 0 || reservationResult.missingMapping > 0 || reservationResult.missingStock > 0),
  );
  const settings = await getWarehouseSettings(order.shop.tenantId);
  const shippingInfo = extractOrderShippingInfo(order.payloadJson, order.currency);
  const shippingDescription = buildShippingInfoDescription(shippingInfo);
  const metadata: Record<string, unknown> = {};
  if (stockWarning) {
    metadata.stockWarning = true;
    metadata.reservationIssues = JSON.parse(JSON.stringify(reservationResult?.issues ?? []));
    metadata.autoConfirmBlockedByStockWarning = true;
  }
  if (shippingInfo) {
    metadata.shipping = shippingInfo;
  }
  const shouldAutoConfirm = input.saveAsDraft !== true && (input.forceConfirm === true || settings.autoConfirmWzOnOrder) && !stockWarning;

  const scansByOrderItemId = new Map<string, string>();
  const scansByProductId = new Map<string, string>();
  for (const scan of input.scans ?? []) {
    const scannedEan = scan.scannedEan?.trim();
    if (!scannedEan) continue;
    const orderItemId = scan.orderItemId?.trim();
    const productId = scan.productId?.trim();
    if (orderItemId && !scansByOrderItemId.has(orderItemId)) scansByOrderItemId.set(orderItemId, scannedEan);
    if (productId && !scansByProductId.has(productId)) scansByProductId.set(productId, scannedEan);
  }
  const scannedEanForReservation = (reservation: { orderItemId: string | null; warehouseProductId: string }) => (
    (reservation.orderItemId ? scansByOrderItemId.get(reservation.orderItemId) : undefined)
      ?? scansByProductId.get(reservation.warehouseProductId)
  );

  let document;
  try {
    document = await prisma.$transaction(async (tx) => {
      const documentDate = new Date();
      const number = await generateDocumentNumber(tx, order.shop.tenantId, 'WZ', documentDate);

      const createdDocument = await tx.warehouseDocument.create({
        data: {
          tenantId: order.shop.tenantId,
          number,
          type: 'WZ',
          status: shouldAutoConfirm ? 'CONFIRMED' : 'DRAFT',
          date: documentDate,
          description: [
            `WZ automatyczne dla zamówienia ${order.orderReference}`,
            shippingDescription,
          ].filter(Boolean).join('. '),
          orderId: order.id,
          isAutoGenerated: true,
          metadataJson: Object.keys(metadata).length > 0 ? JSON.parse(JSON.stringify(metadata)) : undefined,
          confirmedAt: shouldAutoConfirm ? new Date() : undefined,
          items: {
            create: activeReservations.map((reservation) => ({
              productId: reservation.warehouseProductId,
              quantity: reservation.quantity,
              reservationId: reservation.id,
              scannedEan: scannedEanForReservation(reservation),
              notes: `Zamówienie ${order.orderReference}`,
            })),
          },
        },
        include: documentDetailInclude,
      });

      if (shouldAutoConfirm) {
        await consumeDocumentReservations(tx, createdDocument.items);
      }

      return createdDocument;
    });
  } catch (error) {
    // Rownolegle wywolanie (webhook + sync) mogl utworzyc WZ chwile temu — czesciowy
    // indeks unikalny warehouse_documents_wz_per_order zwraca P2002; wracamy do
    // istniejacego dokumentu zamiast wywalac cala operacje.
    const isUniqueViolation = error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002';
    if (!isUniqueViolation || input.retryAfterConflict === true) throw error;
    return createWzForOrder(orderId, { ...input, retryAfterConflict: true });
  }

  if (shouldAutoConfirm) {
    await syncStockForProducts(
      Array.from(new Set(document.items.map((item) => item.productId))),
      'DOCUMENT_CONFIRM',
      document.id,
    );
  }

  return { document: await withAuditUsers(document), created: true, confirmed: shouldAutoConfirm };
}

export interface FinalizeOrderShipmentResult {
  status: 'CONFIRMED' | 'ALREADY_CONFIRMED' | 'NONE' | 'FAILED';
  documentNumber?: string;
  reason?: string;
}

/**
 * Wysylka zamowienia to fizyczne wydanie towaru, wiec rezerwacji nie wolno wtedy
 * zwolnic (to oddaloby towar na stan) — trzeba je skonsumowac dokumentem WZ.
 */
export async function finalizeOrderShipment(orderId: string): Promise<FinalizeOrderShipmentResult> {
  const contextTenantId = getTenantId();
  const order = await prisma.order.findFirst({
    where: {
      id: orderId,
      ...(contextTenantId ? { shop: { tenantId: contextTenantId } } : {}),
    },
    include: { shop: true },
  });
  if (!order) return { status: 'NONE', reason: 'Zamówienie nie znalezione' };

  const document = await prisma.warehouseDocument.findFirst({
    where: {
      tenantId: order.shop.tenantId,
      orderId,
      type: 'WZ',
      status: { not: 'CANCELLED' },
    },
    orderBy: { createdAt: 'asc' },
  });

  if (document?.status === 'CONFIRMED') {
    return { status: 'ALREADY_CONFIRMED', documentNumber: document.number };
  }

  try {
    if (document) {
      await syncWzDraftItemsWithReservations(document.id);
      await confirmDocument(document.id);
      return { status: 'CONFIRMED', documentNumber: document.number };
    }

    const activeReservations = await prisma.warehouseReservation.count({
      where: { tenantId: order.shop.tenantId, orderId, status: 'ACTIVE', source: 'LOCAL_STOCK' },
    });
    if (activeReservations === 0) {
      return { status: 'NONE', reason: 'Brak aktywnych rezerwacji lokalnych do wydania' };
    }

    const result = await createWzForOrder(orderId, { forceConfirm: true });
    if (!result.document) {
      return { status: 'NONE', reason: result.skippedReason ?? 'Nie utworzono WZ' };
    }
    return {
      status: result.confirmed ? 'CONFIRMED' : 'NONE',
      documentNumber: result.document.number,
      reason: result.confirmed ? undefined : 'WZ pozostał roboczy',
    };
  } catch (error) {
    return {
      status: 'FAILED',
      documentNumber: document?.number,
      reason: error instanceof Error ? error.message : 'Nie udało się zamknąć WZ przy wysyłce',
    };
  }
}

export async function createZhForOrder(orderId: string): Promise<CreateZhForOrderResult> {
  const contextTenantId = getTenantId();
  const order = await prisma.order.findFirst({
    where: {
      id: orderId,
      ...(contextTenantId ? { shop: { tenantId: contextTenantId } } : {}),
    },
    include: {
      shop: true,
      items: true,
    },
  });

  if (!order) throw new Error('Zamówienie nie znalezione');

  const existingDocuments = await prisma.warehouseDocument.findMany({
    where: {
      tenantId: order.shop.tenantId,
      orderId,
      type: 'ZH',
      status: { not: 'CANCELLED' },
    },
    include: documentDetailInclude,
    orderBy: [{ date: 'asc' }, { createdAt: 'asc' }],
  });

  let activeReservations = await prisma.warehouseReservation.findMany({
    where: {
      tenantId: order.shop.tenantId,
      orderId: order.id,
      status: 'ACTIVE',
      source: 'WHOLESALE_BACKORDER',
    },
    include: {
      orderItem: true,
      warehouseProduct: {
        select: {
          id: true,
          sku: true,
          name: true,
          wholesaleMappings: {
            where: {
              isActive: true,
              lastKnownStock: { gt: new Prisma.Decimal(0) },
              provider: { isActive: true },
            },
            orderBy: [
              { lastKnownPrice: 'asc' },
              { lastSyncAt: 'desc' },
              { updatedAt: 'desc' },
            ],
            select: {
              providerId: true,
              lastKnownPrice: true,
              provider: {
                select: {
                  id: true,
                  name: true,
                },
              },
            },
          },
        },
      },
    },
    orderBy: { createdAt: 'asc' },
  });

  if (activeReservations.length === 0) {
    await reserveOrder(order.id);
    activeReservations = await prisma.warehouseReservation.findMany({
      where: {
        tenantId: order.shop.tenantId,
        orderId: order.id,
        status: 'ACTIVE',
        source: 'WHOLESALE_BACKORDER',
      },
      include: {
        orderItem: true,
        warehouseProduct: {
          select: {
            id: true,
            sku: true,
            name: true,
            wholesaleMappings: {
              where: {
                isActive: true,
                lastKnownStock: { gt: new Prisma.Decimal(0) },
                provider: { isActive: true },
              },
              orderBy: [
                { lastKnownPrice: 'asc' },
                { lastSyncAt: 'desc' },
                { updatedAt: 'desc' },
              ],
              select: {
                providerId: true,
                lastKnownPrice: true,
                provider: {
                  select: {
                    id: true,
                    name: true,
                  },
                },
              },
            },
          },
        },
      },
      orderBy: { createdAt: 'asc' },
    });
  }

  if (activeReservations.length === 0) {
    return { documents: [], createdCount: 0, skippedReason: 'Brak pozycji do domówienia w hurcie' };
  }

  const existingProviderIds = new Set(
    existingDocuments
      .map((document) => metadataString(document.metadataJson, 'providerId'))
      .filter((providerId): providerId is string => Boolean(providerId)),
  );
  const providerGroups = new Map<string, {
    providerName: string;
    itemsByProductId: Map<string, {
      productId: string;
      quantity: number;
      unitPrice?: number;
      notes: string;
    }>;
  }>();
  let missingMappings = 0;

  for (const reservation of activeReservations) {
    const mapping = reservation.warehouseProduct.wholesaleMappings[0];
    const providerId = mapping?.providerId?.trim();
    const providerName = mapping?.provider?.name?.trim();
    if (!providerId || !providerName) {
      missingMappings += 1;
      continue;
    }
    if (existingProviderIds.has(providerId)) continue;

    const group = providerGroups.get(providerId) ?? {
      providerName,
      itemsByProductId: new Map(),
    };
    const existingItem = group.itemsByProductId.get(reservation.warehouseProductId);
    const quantity = numericQuantity(reservation.quantity);
    const orderRef = order.orderReference || order.externalOrderId;
    const notes = `Zamówienie ${orderRef}`;

    if (existingItem) {
      existingItem.quantity += quantity;
    } else {
      group.itemsByProductId.set(reservation.warehouseProductId, {
        productId: reservation.warehouseProductId,
        quantity,
        unitPrice: mapping.lastKnownPrice == null ? undefined : Number(mapping.lastKnownPrice),
        notes,
      });
    }

    providerGroups.set(providerId, group);
  }

  if (providerGroups.size === 0) {
    const existing = await Promise.all(existingDocuments.map((document) => withAuditUsers(document)));
    return {
      documents: existing.filter((document): document is NonNullable<typeof document> => Boolean(document)),
      createdCount: 0,
      skippedReason: existingDocuments.length > 0
        ? 'ZH dla dostawców z tego zamówienia już istnieje'
        : missingMappings > 0
          ? 'Brak aktywnego mapowania hurtowego dla pozycji do domówienia'
          : 'Brak pozycji do domówienia w hurcie',
    };
  }

  const createdDocuments = [];
  for (const [providerId, group] of providerGroups) {
    const document = await createDocument({
      type: 'ZH',
      orderId: order.id,
      description: `Zamówienie hurtowe dla zamówienia ${order.orderReference} - ${group.providerName}`,
      metadataJson: {
        source: 'ORDER_BACKORDER',
        providerId,
        providerName: group.providerName,
        orderReference: order.orderReference,
        externalOrderId: order.externalOrderId,
      },
      items: Array.from(group.itemsByProductId.values()),
    });
    createdDocuments.push(document);
  }

  const documents = await Promise.all(createdDocuments.map((document) => withAuditUsers(document)));
  return {
    documents: documents.filter((document): document is NonNullable<typeof document> => Boolean(document)),
    createdCount: createdDocuments.length,
  };
}

export async function updateDocument(id: string, input: UpdateDocumentInput) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const data: any = {};
  if (input.date !== undefined) data.date = parseDateInput(input.date);
  if (input.description !== undefined) data.description = input.description;
  if (input.orderId !== undefined) data.orderId = input.orderId;

  let preparedItems: PreparedDocumentItem[] | null = null;
  if (input.items !== undefined) {
    // Podmiana pozycji z UI zgubi reservationId (deleteMany+createMany), a stan
    // zdjety przez rezerwacje zostalby zdjety drugi raz przy zatwierdzeniu.
    if (doc.type === 'WZ') {
      const linkedItems = await prisma.warehouseDocumentItem.count({
        where: { documentId: id, reservationId: { not: null } },
      });
      if (linkedItems > 0) {
        throw new Error('Pozycje WZ powiązane z rezerwacjami synchronizuje system — użyj pakowania zamówienia');
      }
    }
    preparedItems = await prepareDocumentItems(tenantId ?? doc.tenantId, input.items, true, doc.type as DocumentType);
  }

  return prisma.$transaction(async (tx) => {
    if (preparedItems) {
      await tx.warehouseDocumentItem.deleteMany({ where: { documentId: id } });
      if (preparedItems.length > 0) {
        await tx.warehouseDocumentItem.createMany({
          data: preparedItems.map((item) => ({
            documentId: id,
            productId: item.productId,
            quantity: item.quantity,
            systemQuantity: item.systemQuantity ?? null,
            barcodeId: item.barcodeId,
            scannedEan: item.scannedEan,
            baseQuantity: item.baseQuantity,
            quantityMultiplier: item.quantityMultiplier,
            unitPrice: item.unitPrice,
            notes: item.notes,
            reservationId: item.reservationId,
          })),
        });
      }
    }

    return tx.warehouseDocument.update({
      where: { id },
      data,
      include: documentDetailInclude,
    });
  });
}

export async function mergeDocumentItem(documentId: string, input: DocumentItemInput) {
  const tenantId = getTenantId();
  const where: any = { id: documentId };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const [preparedItem] = await prepareDocumentItems(tenantId ?? doc.tenantId, [input], true, doc.type as DocumentType);
  if (!preparedItem) throw new Error('Pozycja dokumentu jest wymagana');

  const isInventory = doc.type === 'INW';

  const updatedDocument = await prisma.$transaction(async (tx) => {
    const existingItem = await tx.warehouseDocumentItem.findFirst({
      where: {
        documentId,
        productId: preparedItem.productId,
        ...(isInventory ? {} : { barcodeId: preparedItem.barcodeId ?? null }),
        // Pozycji z rezerwacja nie wolno powiekszac: stan za nia zdjela rezerwacja,
        // a nadwyzka na tej samej pozycji nigdy nie zeszlaby ze stanu. Nadwyzka
        // dostaje osobna pozycje bez rezerwacji (zdejmie stan sama).
        ...(doc.type === 'WZ' ? { reservationId: null } : {}),
      },
    });

    if (existingItem) {
      if (isInventory) {
        await tx.warehouseDocumentItem.update({
          where: { id: existingItem.id },
          data: {
            quantity: preparedItem.quantity,
            systemQuantity: preparedItem.systemQuantity ?? null,
            scannedEan: preparedItem.scannedEan ?? existingItem.scannedEan,
            notes: preparedItem.notes ?? existingItem.notes,
          },
        });
      } else {
        await tx.warehouseDocumentItem.update({
          where: { id: existingItem.id },
          data: {
            quantity: new Prisma.Decimal(existingItem.quantity).plus(preparedItem.quantity),
            baseQuantity:
              existingItem.baseQuantity || preparedItem.baseQuantity
                ? new Prisma.Decimal(existingItem.baseQuantity ?? 0).plus(preparedItem.baseQuantity ?? 0)
                : null,
            quantityMultiplier: existingItem.quantityMultiplier ?? preparedItem.quantityMultiplier,
            scannedEan: existingItem.scannedEan ?? preparedItem.scannedEan,
            unitPrice: existingItem.unitPrice ?? preparedItem.unitPrice,
            notes: existingItem.notes || preparedItem.notes,
          },
        });
      }
    } else {
      await tx.warehouseDocumentItem.create({
        data: {
          documentId,
          productId: preparedItem.productId,
          quantity: preparedItem.quantity,
          systemQuantity: preparedItem.systemQuantity ?? null,
          barcodeId: preparedItem.barcodeId,
          scannedEan: preparedItem.scannedEan,
          baseQuantity: preparedItem.baseQuantity,
          quantityMultiplier: preparedItem.quantityMultiplier,
          unitPrice: preparedItem.unitPrice,
          notes: preparedItem.notes,
          reservationId: preparedItem.reservationId,
        },
      });
    }

    return tx.warehouseDocument.findUnique({
      where: { id: documentId },
      include: documentDetailInclude,
    });
  });

  return updatedDocument;
}

export async function bulkUpsertInventoryItems(documentId: string, input: BulkUpsertInventoryItemsInput) {
  const tenantId = getTenantId();
  const documentWhere: any = { id: documentId };
  if (tenantId) documentWhere.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where: documentWhere });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');
  if (doc.type !== 'INW') throw new Error('Bulk zapis pozycji jest dostępny tylko dla dokumentu INW');
  if (!Array.isArray(input.items) || input.items.length === 0) throw new Error('Brak pozycji do zapisania');

  const preparedItems = await prepareDocumentItems(tenantId ?? doc.tenantId, input.items, true, 'INW');

  return prisma.$transaction(async (tx) => {
    const existingItems = await tx.warehouseDocumentItem.findMany({
      where: {
        documentId,
        productId: { in: preparedItems.map((item) => item.productId) },
      },
      select: { id: true, productId: true },
    });
    const existingByProductId = new Map(existingItems.map((item) => [item.productId, item.id]));
    const createItems: Prisma.WarehouseDocumentItemCreateManyInput[] = [];

    for (const item of preparedItems) {
      const data = {
        quantity: item.quantity,
        systemQuantity: item.systemQuantity ?? null,
        notes: item.notes,
        scannedEan: item.scannedEan,
      };
      const existingId = existingByProductId.get(item.productId);

      if (existingId) {
        await tx.warehouseDocumentItem.update({
          where: { id: existingId },
          data,
        });
      } else {
        createItems.push({
          documentId,
          productId: item.productId,
          barcodeId: item.barcodeId,
          baseQuantity: item.baseQuantity,
          quantityMultiplier: item.quantityMultiplier,
          unitPrice: item.unitPrice,
          reservationId: item.reservationId,
          ...data,
        });
      }
    }

    if (createItems.length > 0) {
      await tx.warehouseDocumentItem.createMany({ data: createItems });
    }

    return tx.warehouseDocument.findUnique({
      where: { id: documentId },
      include: { order: true },
    });
  });
}

export async function updateDocumentItem(documentId: string, itemId: string, input: UpdateDocumentItemInput) {
  const tenantId = getTenantId();
  const documentWhere: any = { id: documentId };
  if (tenantId) documentWhere.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where: documentWhere });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const item = await prisma.warehouseDocumentItem.findFirst({ where: { id: itemId, documentId } });
  if (!item) throw new Error('Pozycja dokumentu nie znaleziona');

  const isInventory = doc.type === 'INW';

  const data: Prisma.WarehouseDocumentItemUpdateInput = {};
  if (input.quantity !== undefined) {
    if (isInventory) {
      if (input.quantity < 0) throw new Error('Stan policzony nie może być ujemny');
    } else if (input.quantity <= 0) {
      throw new Error('Ilość pozycji musi być większa od 0');
    }
    // Ilosc pozycji z rezerwacja dyktuje rezerwacja (stan zdjeto wg niej) — reczna
    // zmiana rozjechalaby dokument z magazynem.
    if (doc.type === 'WZ' && item.reservationId) {
      throw new Error('Ilość pozycji WZ powiązanej z rezerwacją zmienia się przez rezerwacje zamówienia');
    }
    data.quantity = input.quantity;
  }
  if (input.systemQuantity !== undefined) {
    if (!isInventory) throw new Error('Stan systemowy można aktualizować tylko w dokumencie INW');
    if (input.systemQuantity !== null && input.systemQuantity < 0) throw new Error('Stan systemowy nie może być ujemny');
    data.systemQuantity = input.systemQuantity;
  }
  if (input.baseQuantity !== undefined) {
    if (input.baseQuantity !== null && input.baseQuantity <= 0) throw new Error('Ilość bazowa musi być większa od 0');
    data.baseQuantity = input.baseQuantity;
  }
  if (input.quantityMultiplier !== undefined) {
    if (input.quantityMultiplier !== null && input.quantityMultiplier <= 0) throw new Error('Przelicznik EAN musi być większy od 0');
    data.quantityMultiplier = input.quantityMultiplier;
  }
  if (input.unitPrice !== undefined) {
    if (input.unitPrice !== null && input.unitPrice < 0) throw new Error('Cena pozycji nie może być ujemna');
    data.unitPrice = input.unitPrice;
  }
  if (input.notes !== undefined) data.notes = input.notes;

  await prisma.warehouseDocumentItem.update({
    where: { id: itemId },
    data,
  });

  return prisma.warehouseDocument.findUnique({
    where: { id: documentId },
    include: documentDetailInclude,
  });
}

export async function deleteDocumentItem(documentId: string, itemId: string) {
  const tenantId = getTenantId();
  const documentWhere: any = { id: documentId };
  if (tenantId) documentWhere.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where: documentWhere });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const item = await prisma.warehouseDocumentItem.findFirst({ where: { id: itemId, documentId } });
  if (!item) throw new Error('Pozycja dokumentu nie znaleziona');

  await prisma.warehouseDocumentItem.delete({ where: { id: itemId } });

  return prisma.warehouseDocument.findUnique({
    where: { id: documentId },
    include: documentDetailInclude,
  });
}

/**
 * Rezerwacja przypieta do pozycji WZ moze byc juz nieaktywna, jesli zamowienie
 * zmienilo status (np. na SHIPPED) zanim ktos zatwierdzil roboczy dokument.
 * Zwolnienie rezerwacji LOCAL_STOCK oddaje towar na stan, wiec taka pozycja musi
 * przy zatwierdzeniu zdjac stan samodzielnie (DETACH). Rezerwacje hurtowe nigdy
 * nie ruszaly stanu, wiec zostaja bez zmiany stanu (SKIP).
 */
type WzReservationDisposition = 'CONSUME' | 'DETACH' | 'DETACH_CANCEL' | 'SKIP';

async function resolveWzReservationDispositions(
  type: DocumentType,
  items: Array<{ id: string; reservationId?: string | null }>,
): Promise<Map<string, WzReservationDisposition>> {
  const dispositions = new Map<string, WzReservationDisposition>();
  if (type !== 'WZ') return dispositions;

  const reservationIds = items
    .map((item) => item.reservationId)
    .filter((reservationId): reservationId is string => Boolean(reservationId));
  if (reservationIds.length === 0) return dispositions;

  const reservations = await prisma.warehouseReservation.findMany({
    where: { id: { in: reservationIds } },
    select: { id: true, status: true, source: true },
  });
  const reservationById = new Map(reservations.map((reservation) => [reservation.id, reservation]));

  for (const item of items) {
    if (!item.reservationId) continue;
    const reservation = reservationById.get(item.reservationId);
    if (!reservation) {
      dispositions.set(item.id, 'DETACH');
      continue;
    }
    if (reservation.status === 'ACTIVE' && reservation.source === 'WHOLESALE_BACKORDER') {
      // Backorder nie zajal stanu, wiec wydanie musi zdjac stan samo, a rezerwacje
      // hurtowa zamykamy — towar wyjezdza, nie ma juz czego domawiac.
      dispositions.set(item.id, 'DETACH_CANCEL');
      continue;
    }
    if (reservation.status === 'ACTIVE' || reservation.status === 'CONSUMED') {
      dispositions.set(item.id, 'CONSUME');
      continue;
    }
    dispositions.set(item.id, reservation.source === 'LOCAL_STOCK' ? 'DETACH' : 'SKIP');
  }

  return dispositions;
}

export async function confirmDocument(id: string) {
  const tenantId = getTenantId();
  const context = getTenantContext();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({
    where,
    include: { items: { include: { product: true } } },
  });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Tylko dokumenty DRAFT można zatwierdzić');

  if (doc.items.length === 0) throw new Error('Dokument nie ma żadnych pozycji');

  const dispositions = await resolveWzReservationDispositions(doc.type, doc.items);
  // Pozycje z martwa rezerwacja (LOCAL_STOCK juz zwolniona) oraz z aktywnym backorderem
  // musza same zdjac stan — rezerwacja albo oddala towar na magazyn, albo nigdy go nie zajela.
  const isDetached = (item: { id: string }) => {
    const disposition = dispositions.get(item.id);
    return disposition === 'DETACH' || disposition === 'DETACH_CANCEL';
  };
  const stockItems = doc.items.map((item) => (
    isDetached(item) ? { ...item, reservationId: null } : item
  ));
  const consumableItems = doc.items.filter((item) => dispositions.get(item.id) === 'CONSUME');
  const detachedItemIds = doc.items.filter(isDetached).map((item) => item.id);
  const backorderReservationIdsToCancel = doc.items
    .filter((item) => dispositions.get(item.id) === 'DETACH_CANCEL')
    .map((item) => item.reservationId)
    .filter((reservationId): reservationId is string => Boolean(reservationId));

  await assertFullInventoryComplete(doc.tenantId, doc.type, doc.metadataJson, doc.items);
  await assertCanConfirmWithoutNegativeStock(doc.tenantId, doc.type, stockItems);

  const confirmedDocument = await prisma.$transaction(async (tx) => {
    await applyIncomingPurchaseCosts(tx, doc.type, doc.items);
    await applyStockDeltas(tx, doc.type, stockItems);
    await consumeDocumentReservations(tx, consumableItems);
    if (detachedItemIds.length > 0) {
      await tx.warehouseDocumentItem.updateMany({
        where: { id: { in: detachedItemIds } },
        data: { reservationId: null },
      });
    }
    if (backorderReservationIdsToCancel.length > 0) {
      // Bez ruchu stanu: backorder nigdy nie zajal currentStock.
      await tx.warehouseReservation.updateMany({
        where: { id: { in: backorderReservationIdsToCancel }, status: 'ACTIVE' },
        data: {
          status: 'CANCELLED',
          cancelledAt: new Date(),
          reason: 'Pozycja wydana dokumentem WZ bez pokrycia lokalnego',
        },
      });
    }

    return tx.warehouseDocument.update({
      where: { id },
      data: {
        status: 'CONFIRMED',
        confirmedAt: new Date(),
        confirmedByUserId: context?.userId,
      },
        include: documentDetailInclude,
    });
  }, { timeout: 20000 });

  const affectedProductIds = Array.from(new Set(doc.items.map((item) => item.productId)));
  if (doc.type === 'PZ') {
    await reallocateWholesaleBackordersForProducts(doc.tenantId, affectedProductIds);
  }

  await syncStockForProducts(
    affectedProductIds,
    'DOCUMENT_CONFIRM',
    id,
  );

  return confirmedDocument;
}

async function reallocateWholesaleBackordersForProducts(tenantId: string, productIds: string[]) {
  const uniqueProductIds = Array.from(new Set(productIds.filter(Boolean)));
  if (uniqueProductIds.length === 0) return;

  const reservations = await prisma.warehouseReservation.findMany({
    where: {
      tenantId,
      status: 'ACTIVE',
      source: 'WHOLESALE_BACKORDER',
      warehouseProductId: { in: uniqueProductIds },
      order: {
        operationalStatus: { in: STOCK_RESERVATION_ORDER_OPERATIONAL_STATUSES },
      },
    },
    select: { orderId: true },
  });

  const orderIds = Array.from(new Set(reservations.map((reservation) => reservation.orderId)));
  for (const orderId of orderIds) {
    await reserveOrder(orderId);
  }

  // Realokacja wymienila rezerwacje (nowe id) — robocze WZ tych zamowien musza
  // dostac pozycje wskazujace nowe rezerwacje, inaczej zatwierdzenie nie zdejmie stanu.
  if (orderIds.length > 0) {
    const draftDocuments = await prisma.warehouseDocument.findMany({
      where: { tenantId, orderId: { in: orderIds }, type: 'WZ', status: 'DRAFT' },
      select: { id: true },
    });
    for (const draft of draftDocuments) {
      await syncWzDraftItemsWithReservations(draft.id);
    }
  }
}

async function assertCanConfirmWithoutNegativeStock(
  tenantId: string,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; systemQuantity?: Prisma.Decimal | null; reservationId?: string | null; product: { name: string; unit: string } }>,
) {
  if (type === 'INW') {
    for (const item of items) {
      if (Number(item.quantity) < 0) {
        throw new Error(`Stan policzony produktu "${item.product.name}" nie może być ujemny`);
      }
    }
    return;
  }

  if (!['WZ', 'RW'].includes(type)) return;

  const settings = await getWarehouseSettings(tenantId);
  if (settings.allowNegativeStock) return;

  const requestedByProduct = new Map<string, { quantity: number; name: string; unit: string }>();

  for (const item of items) {
    if (type === 'WZ' && item.reservationId) continue;

    const existing = requestedByProduct.get(item.productId);
    const quantity = Number(item.quantity);

    if (existing) {
      existing.quantity += quantity;
    } else {
      requestedByProduct.set(item.productId, {
        quantity,
        name: item.product.name,
        unit: item.product.unit,
      });
    }
  }

  if (requestedByProduct.size === 0) return;

  const products = await prisma.warehouseProduct.findMany({
    where: { tenantId, id: { in: Array.from(requestedByProduct.keys()) } },
    select: { id: true, currentStock: true },
  });
  const stockByProductId = new Map(products.map((product) => [product.id, Number(product.currentStock)]));

  for (const [productId, requested] of requestedByProduct) {
    const stock = stockByProductId.get(productId) ?? 0;
    const requestedQuantity = requested.quantity;
    const nextStock = stock - requestedQuantity;

    if (nextStock < 0) {
      throw new Error(
        `Niewystarczający stan produktu "${requested.name}": dostępne ${stock} ${requested.unit}, wymagane ${requestedQuantity} ${requested.unit}`,
      );
    }
  }
}

async function assertFullInventoryComplete(
  tenantId: string,
  type: string,
  metadataJson: Prisma.JsonValue | null,
  items: Array<{ productId: string }>,
) {
  if (type !== 'INW') return;
  const metadata = metadataRecord(metadataJson);
  if (metadata.inventoryScope !== FULL_INVENTORY_SCOPE) return;

  const activeProducts = await prisma.warehouseProduct.findMany({
    where: { tenantId, isActive: true, isStockTracked: true },
    select: { id: true, sku: true, name: true },
    orderBy: [{ sku: 'asc' }, { name: 'asc' }],
  });

  const itemProductIds = new Set(items.map((item) => item.productId));
  const missingProducts = activeProducts.filter((product) => !itemProductIds.has(product.id));
  if (missingProducts.length === 0) return;

  const preview = missingProducts
    .slice(0, 5)
    .map((product) => `${product.sku} ${product.name}`)
    .join(', ');
  const suffix = missingProducts.length > 5 ? ` i ${missingProducts.length - 5} kolejnych` : '';
  throw new Error(`Pełna inwentaryzacja wymaga policzenia wszystkich aktywnych produktów śledzonych w magazynie. Brakuje ${missingProducts.length}: ${preview}${suffix}`);
}

async function getWarehouseSettings(tenantId: string) {
  const tenant = await prisma.tenant.findUnique({
    where: { id: tenantId },
    select: { limitsJson: true },
  });

  const limits = tenant?.limitsJson as any;
  return {
    allowNegativeStock: limits?.warehouse?.allowNegativeStock === true,
    autoCreateWzOnOrder: limits?.warehouse?.autoCreateWzOnOrder !== false,
    autoConfirmWzOnOrder: limits?.warehouse?.autoConfirmWzOnOrder === true,
  };
}

export async function shouldAutoCreateWzForTenant(tenantId: string) {
  const settings = await getWarehouseSettings(tenantId);
  return settings.autoCreateWzOnOrder;
}

export async function cancelDocument(id: string, input: CancelDocumentInput = {}) {
  const tenantId = getTenantId();
  const context = getTenantContext();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({
    where,
    include: { items: true },
  });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status === 'CANCELLED') throw new Error('Dokument jest już anulowany');

  const cancelledDocument = await prisma.$transaction(async (tx) => {
    if (doc.status === 'CONFIRMED') {
      await applyStockDeltas(tx, doc.type, doc.items, true);
      await releaseDocumentReservations(tx, doc.items);
    }

    return tx.warehouseDocument.update({
      where: { id },
      data: {
        status: 'CANCELLED',
        cancelledAt: new Date(),
        cancelledByUserId: context?.userId,
        cancelReason: input.reason,
      },
      include: documentDetailInclude,
    });
  });

  if (doc.status === 'CONFIRMED') {
    await syncStockForProducts(
      doc.items.map((item) => item.productId),
      'DOCUMENT_CANCEL',
      id,
    );
  }

  return cancelledDocument;
}

export async function deleteDocument(id: string) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można usunąć tylko dokumenty w statusie DRAFT');

  return prisma.warehouseDocument.delete({ where: { id } });
}

async function prepareDocumentItems(
  tenantId: string,
  items: DocumentItemInput[],
  requireActiveProduct: boolean,
  type?: DocumentType,
): Promise<PreparedDocumentItem[]> {
  const isInventory = type === 'INW';
  const preparedItems: PreparedDocumentItem[] = [];
  const productIds = Array.from(new Set(items.map((item) => item.productId).filter(Boolean)));
  const barcodeIds = Array.from(new Set(items.map((item) => item.barcodeId).filter(Boolean) as string[]));

  if (isInventory) {
    const seen = new Set<string>();
    for (const item of items) {
      if (seen.has(item.productId)) {
        throw new Error('W dokumencie INW każdy produkt może wystąpić tylko raz');
      }
      seen.add(item.productId);
    }
  }

  const productSelect = isInventory
    ? { id: true, name: true, isActive: true, currentStock: true }
    : { id: true, name: true, isActive: true };

  const reservationsPromise = isInventory && productIds.length > 0
    ? prisma.warehouseReservation.groupBy({
        by: ['warehouseProductId'],
        where: {
          tenantId,
          warehouseProductId: { in: productIds },
          status: 'ACTIVE',
          source: 'LOCAL_STOCK',
        },
        _sum: { quantity: true },
      })
    : Promise.resolve([]);

  const [products, barcodes, reservationGroups] = await Promise.all([
    prisma.warehouseProduct.findMany({
      where: { id: { in: productIds }, tenantId },
      select: productSelect,
    }),
    barcodeIds.length > 0
      ? prisma.warehouseProductBarcode.findMany({
          where: { id: { in: barcodeIds }, tenantId },
          select: {
            id: true,
            warehouseProductId: true,
            ean: true,
            quantityMultiplier: true,
            isActive: true,
          },
        })
      : Promise.resolve([]),
    reservationsPromise,
  ]);

  const productById = new Map(products.map((product) => [product.id, product as typeof product & { currentStock?: Prisma.Decimal }]));
  const barcodeById = new Map(barcodes.map((barcode) => [barcode.id, barcode]));
  const reservedByProductId = new Map(
    reservationGroups.map((row) => [row.warehouseProductId, new Prisma.Decimal(row._sum.quantity ?? 0)]),
  );

  for (const item of items) {
    const product = productById.get(item.productId);
    if (!product) throw new Error(`Produkt ${item.productId} nie znaleziony`);
    if (requireActiveProduct && !product.isActive) throw new Error(`Produkt "${product.name}" jest nieaktywny`);

    let scannedEan = item.scannedEan?.trim() || undefined;
    let quantityMultiplier = item.quantityMultiplier;
    const barcodeId = item.barcodeId;

    if (barcodeId) {
      const barcode = barcodeById.get(barcodeId);
      if (!barcode) throw new Error(`Kod EAN ${barcodeId} nie znaleziony dla produktu "${product.name}"`);
      if (barcode.warehouseProductId !== item.productId) {
        throw new Error(`Kod EAN ${barcodeId} nie znaleziony dla produktu "${product.name}"`);
      }
      if (!barcode.isActive) throw new Error(`Kod EAN "${barcode.ean}" jest nieaktywny`);
      scannedEan = scannedEan ?? barcode.ean;
      quantityMultiplier = quantityMultiplier ?? Number(barcode.quantityMultiplier);
    }

    const minQuantity = isInventory ? 0 : 0; // próg dolny włącznie — INW dopuszcza 0
    const requireStrictPositive = !isInventory;

    const baseQuantity = item.baseQuantity ?? item.quantity;
    if (baseQuantity === undefined || (requireStrictPositive ? baseQuantity <= 0 : baseQuantity < minQuantity)) {
      throw new Error(isInventory ? 'Stan policzony nie może być ujemny' : 'Ilość pozycji musi być większa od 0');
    }

    quantityMultiplier = quantityMultiplier ?? 1;
    if (quantityMultiplier <= 0) throw new Error('Przelicznik EAN musi być większy od 0');

    const quantity = item.quantity ?? baseQuantity * quantityMultiplier;
    if (requireStrictPositive ? quantity <= 0 : quantity < minQuantity) {
      throw new Error(isInventory ? 'Stan policzony nie może być ujemny' : 'Ilość pozycji musi być większa od 0');
    }

    let systemQuantity: number | null | undefined;
    if (isInventory) {
      if (item.systemQuantity === null || item.systemQuantity === undefined) {
        const availableStock = new Prisma.Decimal(product.currentStock ?? 0);
        const reservedQuantity = reservedByProductId.get(item.productId) ?? new Prisma.Decimal(0);
        systemQuantity = Number(availableStock.plus(reservedQuantity));
      } else {
        systemQuantity = Number(item.systemQuantity);
        if (!Number.isFinite(systemQuantity)) {
          throw new Error('Stan systemowy jest nieprawidłowy');
        }
      }
    }

    preparedItems.push({
      productId: item.productId,
      quantity,
      systemQuantity,
      barcodeId,
      scannedEan,
      baseQuantity,
      quantityMultiplier,
      unitPrice: item.unitPrice,
      notes: item.notes,
      reservationId: item.reservationId ?? null,
    });
  }

  return preparedItems;
}

async function applyStockDeltas(
  tx: Prisma.TransactionClient,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; systemQuantity?: Prisma.Decimal | null; reservationId?: string | null }>,
  reverse = false,
) {
  if (type === 'INW') {
    const deltas = new Map<string, Prisma.Decimal>();
    for (const item of items) {
      const counted = new Prisma.Decimal(item.quantity);
      const system = new Prisma.Decimal(item.systemQuantity ?? 0);
      const delta = reverse ? system.minus(counted) : counted.minus(system);
      deltas.set(item.productId, (deltas.get(item.productId) ?? new Prisma.Decimal(0)).plus(delta));
    }
    for (const [productId, delta] of deltas) {
      if (delta.equals(0)) continue;
      await tx.warehouseProduct.update({
        where: { id: productId },
        data: { currentStock: { increment: delta } },
      });
    }
    return;
  }

  const baseSign = getStockDeltaSign(type);
  if (baseSign === 0) return;

  const sign = reverse ? -baseSign : baseSign;
  const deltas = new Map<string, Prisma.Decimal>();

  for (const item of items) {
    if (type === 'WZ' && item.reservationId) continue;

    const current = deltas.get(item.productId) ?? new Prisma.Decimal(0);
    deltas.set(item.productId, current.plus(item.quantity.mul(sign)));
  }

  for (const [productId, delta] of deltas) {
    await tx.warehouseProduct.update({
      where: { id: productId },
      data: { currentStock: { increment: delta } },
    });
  }
}

async function applyIncomingPurchaseCosts(
  tx: Prisma.TransactionClient,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; unitPrice?: Prisma.Decimal | null }>,
) {
  if (type !== 'PZ') return;

  const incomingByProduct = new Map<string, { quantity: Prisma.Decimal; value: Prisma.Decimal }>();
  for (const item of items) {
    if (item.unitPrice === null || item.unitPrice === undefined) continue;
    const quantity = new Prisma.Decimal(item.quantity);
    if (quantity.lte(0)) continue;
    const value = quantity.mul(item.unitPrice);
    const current = incomingByProduct.get(item.productId) ?? {
      quantity: new Prisma.Decimal(0),
      value: new Prisma.Decimal(0),
    };
    incomingByProduct.set(item.productId, {
      quantity: current.quantity.plus(quantity),
      value: current.value.plus(value),
    });
  }

  for (const [productId, incoming] of incomingByProduct) {
    const product = await tx.warehouseProduct.findUnique({
      where: { id: productId },
      select: { currentStock: true, averagePurchaseCost: true, purchasePrice: true },
    });
    if (!product) continue;

    const currentStock = Prisma.Decimal.max(new Prisma.Decimal(product.currentStock), new Prisma.Decimal(0));
    const currentCost = new Prisma.Decimal(product.averagePurchaseCost ?? product.purchasePrice ?? 0);
    const nextStock = currentStock.plus(incoming.quantity);
    const nextCost = currentStock.gt(0) && currentCost.gt(0)
      ? currentStock.mul(currentCost).plus(incoming.value).div(nextStock)
      : incoming.value.div(incoming.quantity);

    await tx.warehouseProduct.update({
      where: { id: productId },
      data: { averagePurchaseCost: new Prisma.Decimal(nextCost.toFixed(2)) },
    });
  }
}

function getStockDeltaSign(type: DocumentType) {
  if (STOCK_INCOMING_TYPES.includes(type)) return 1;
  if (STOCK_OUTGOING_TYPES.includes(type)) return -1;
  return 0;
}

// ─── Numeracja dokumentów ─────────────────────────────────────────────────────

async function generateDocumentNumber(
  tx: Prisma.TransactionClient,
  tenantId: string,
  type: DocumentType,
  documentDate = new Date(),
): Promise<string> {
  const year = documentDate.getFullYear();
  const prefix = `${type}/${year}/`;
  const lockKey = `${tenantId}:${type}:${year}`;

  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${lockKey}))`;

  const rows = await tx.$queryRaw<Array<{ max: number | bigint | string | null }>>`
    SELECT COALESCE(MAX(CAST(split_part("number", '/', 3) AS INTEGER)), 0) AS max
    FROM "warehouse_documents"
    WHERE "tenant_id" = ${tenantId}
      AND "number" LIKE ${prefix + '%'}
      AND split_part("number", '/', 3) ~ '^[0-9]+$'
  `;
  const seq = Number(rows[0]?.max ?? 0) + 1;

  return `${prefix}${String(seq).padStart(3, '0')}`;
}
