import prisma from '../../lib/prisma';
import { Prisma } from '@prisma/client';
import { getTenantContext, getTenantId } from '../../lib/tenant-context';
import { syncStockForProducts } from '../stock/stock-sync.service';
import { consumeDocumentReservations, releaseDocumentReservations, reserveOrder } from './warehouse-reservations.service';
import { buildShippingInfoDescription, extractOrderShippingInfo } from '../orders/order-shipping-info.service';
import { STOCK_RESERVATION_ORDER_OPERATIONAL_STATUSES } from '../../lib/order-statuses';

// ─── Documents ───────────────────────────────────────────────────────────────

export type DocumentType = 'PZ' | 'ZH' | 'PW' | 'WZ' | 'ZW' | 'RW' | 'INW';
const STOCK_INCOMING_TYPES: DocumentType[] = ['PZ', 'PW', 'ZW'];
const STOCK_OUTGOING_TYPES: DocumentType[] = ['WZ', 'RW'];

export interface DocumentItemInput {
  productId: string;
  quantity?: number;
  /** Wymagany tylko dla INW: snapshot stanu systemowego z momentu wpisania pozycji. Jeśli null, serwis bierze bieżący `currentStock`. */
  systemQuantity?: number | null;
  barcodeId?: string;
  scannedEan?: string;
  baseQuantity?: number;
  quantityMultiplier?: number;
  unitPrice?: number;
  notes?: string;
  reservationId?: string | null;
}

export interface CreateDocumentInput {
  type: DocumentType;
  date?: string;
  description?: string;
  orderId?: string;
  isAutoGenerated?: boolean;
  metadataJson?: Prisma.InputJsonValue;
  items: DocumentItemInput[];
}

export interface UpdateDocumentInput {
  date?: string;
  description?: string;
  orderId?: string | null;
  items?: DocumentItemInput[];
}

export interface UpdateDocumentItemInput {
  quantity?: number;
  /** Tylko INW: aktualizacja snapshotu stanu systemowego (np. po wyborze "odśwież snapshot"). */
  systemQuantity?: number | null;
  baseQuantity?: number | null;
  quantityMultiplier?: number | null;
  unitPrice?: number | null;
  notes?: string | null;
}

export interface CancelDocumentInput {
  reason?: string;
}

export interface CreateWzForOrderResult {
  document: Awaited<ReturnType<typeof getDocumentById>>;
  created: boolean;
  skippedReason?: string;
}

export interface CreateWzForOrderInput {
  saveAsDraft?: boolean;
  forceConfirm?: boolean;
}

export interface CreatePzFromWholesaleOrderResult {
  document: Awaited<ReturnType<typeof getDocumentById>>;
  created: boolean;
  skippedReason?: string;
}

export interface CreatePzFromWholesaleOrderInput {
  items?: DocumentItemInput[];
  saveAsDraft?: boolean;
}

export interface WholesaleOrderCsvExportResult {
  providerId: string | null;
  providerName: string | null;
  filename: string;
  content: string;
  mimeType: string;
  rows: number;
  confirmedDocuments: number;
  document?: Awaited<ReturnType<typeof getDocumentById>>;
  documents?: Array<NonNullable<Awaited<ReturnType<typeof getDocumentById>>>>;
}

export interface DocumentsQuery {
  page?: number;
  limit?: number;
  search?: string;
  type?: DocumentType;
  status?: 'DRAFT' | 'CONFIRMED' | 'CANCELLED';
  dateFrom?: string;
  dateTo?: string;
  isAutoGenerated?: boolean | string;
  stockWarning?: boolean | string;
}

interface PreparedDocumentItem {
  productId: string;
  quantity: number;
  systemQuantity?: number | null;
  barcodeId?: string;
  scannedEan?: string;
  baseQuantity?: number;
  quantityMultiplier?: number;
  unitPrice?: number;
  notes?: string;
  reservationId?: string | null;
}

const documentDetailInclude = {
  items: {
    include: {
      product: {
        include: {
          wholesaleMappings: {
            where: {
              isActive: true,
              provider: { isActive: true },
            },
            include: {
              provider: {
                select: {
                  id: true,
                  name: true,
                  configJson: true,
                },
              },
            },
            orderBy: [{ lastSyncAt: 'desc' }, { updatedAt: 'desc' }],
            take: 10,
          },
        },
      },
      barcode: true,
      reservation: true,
    },
  },
  order: true,
} satisfies Prisma.WarehouseDocumentInclude;

function normalizeBooleanQuery(value: boolean | string | undefined) {
  if (value === undefined) return undefined;
  if (value === true || value === 'true') return true;
  if (value === false || value === 'false') return false;
  return undefined;
}

function parseDateInput(value: string) {
  const trimmed = value.trim();
  const dateOnlyMatch = /^(\d{4})-(\d{2})-(\d{2})$/.exec(trimmed);
  if (dateOnlyMatch) {
    const [, year, month, day] = dateOnlyMatch;
    return new Date(Number(year), Number(month) - 1, Number(day));
  }
  return new Date(trimmed);
}

function startOfDay(value: string) {
  const date = parseDateInput(value);
  date.setHours(0, 0, 0, 0);
  return date;
}

function endOfDay(value: string) {
  const date = parseDateInput(value);
  date.setHours(23, 59, 59, 999);
  return date;
}

async function withAuditUsers<T extends {
  createdByUserId?: string | null;
  confirmedByUserId?: string | null;
  cancelledByUserId?: string | null;
} | null>(document: T) {
  if (!document) return document;

  const userIds = Array.from(new Set([
    document.createdByUserId,
    document.confirmedByUserId,
    document.cancelledByUserId,
  ].filter((id): id is string => Boolean(id))));

  if (userIds.length === 0) {
    return {
      ...document,
      createdByUser: null,
      confirmedByUser: null,
      cancelledByUser: null,
    };
  }

  const users = await prisma.user.findMany({
    where: { id: { in: userIds } },
    select: { id: true, name: true, email: true },
  });
  const userById = new Map(users.map((user) => [user.id, user]));

  return {
    ...document,
    createdByUser: document.createdByUserId ? userById.get(document.createdByUserId) ?? null : null,
    confirmedByUser: document.confirmedByUserId ? userById.get(document.confirmedByUserId) ?? null : null,
    cancelledByUser: document.cancelledByUserId ? userById.get(document.cancelledByUserId) ?? null : null,
  };
}

export async function getDocuments(query: DocumentsQuery = {}) {
  const tenantId = getTenantId();
  const { page = 1, limit = 20, search, type, status, dateFrom, dateTo } = query;
  const skip = (page - 1) * limit;
  const isAutoGenerated = normalizeBooleanQuery(query.isAutoGenerated);
  const stockWarning = normalizeBooleanQuery(query.stockWarning);
  const searchTerm = search?.trim();

  const where: any = {};
  if (tenantId) where.tenantId = tenantId;
  if (searchTerm) {
    where.OR = [
      { number: { contains: searchTerm, mode: 'insensitive' } },
      { description: { contains: searchTerm, mode: 'insensitive' } },
      { order: { is: { orderReference: { contains: searchTerm, mode: 'insensitive' } } } },
      { order: { is: { externalOrderId: { contains: searchTerm, mode: 'insensitive' } } } },
    ];
  }
  if (type) where.type = type;
  if (status) where.status = status;
  if (isAutoGenerated !== undefined) where.isAutoGenerated = isAutoGenerated;
  if (stockWarning !== undefined) where.metadataJson = { path: ['stockWarning'], equals: stockWarning };
  if (dateFrom || dateTo) {
    where.date = {};
    if (dateFrom) where.date.gte = startOfDay(dateFrom);
    if (dateTo) where.date.lte = endOfDay(dateTo);
  }

  const monthStart = new Date();
  monthStart.setDate(1);
  monthStart.setHours(0, 0, 0, 0);
  const monthEnd = new Date(monthStart);
  monthEnd.setMonth(monthEnd.getMonth() + 1);
  monthEnd.setMilliseconds(-1);
  const tenantWhere = tenantId ? { tenantId } : {};

  const [documents, total, stockWarningCount, confirmedThisMonth, autoWzFromOrders] = await Promise.all([
    prisma.warehouseDocument.findMany({
      where,
      skip,
      take: limit,
      orderBy: [{ date: 'desc' }, { createdAt: 'desc' }],
      select: {
        id: true,
        tenantId: true,
        number: true,
        type: true,
        status: true,
        date: true,
        description: true,
        orderId: true,
        createdByUserId: true,
        confirmedAt: true,
        confirmedByUserId: true,
        cancelledAt: true,
        cancelledByUserId: true,
        cancelReason: true,
        isAutoGenerated: true,
        metadataJson: true,
        createdAt: true,
        updatedAt: true,
        order: { select: { id: true, orderReference: true, externalOrderId: true } },
        _count: { select: { items: true } },
      },
    }),
    prisma.warehouseDocument.count({ where }),
    prisma.warehouseDocument.count({
      where: {
        ...tenantWhere,
        metadataJson: { path: ['stockWarning'], equals: true },
      } as any,
    }),
    prisma.warehouseDocument.count({
      where: {
        ...tenantWhere,
        status: 'CONFIRMED',
        date: { gte: monthStart, lte: monthEnd },
      },
    }),
    prisma.warehouseDocument.count({
      where: {
        ...tenantWhere,
        type: 'WZ',
        isAutoGenerated: true,
        orderId: { not: null },
      },
    }),
  ]);
  const documentIds = documents.map((document) => document.id);
  const [quantityGroups, valueGroups] = documentIds.length === 0
    ? [[], []] as const
    : await Promise.all([
      prisma.warehouseDocumentItem.groupBy({
        by: ['documentId'],
        where: { documentId: { in: documentIds } },
        _sum: { quantity: true },
      }),
      prisma.$queryRaw<Array<{ documentId: string; totalValue: Prisma.Decimal | number | string | null }>>`
        SELECT document_id AS "documentId",
               COALESCE(SUM(quantity * COALESCE(unit_price, 0)), 0) AS "totalValue"
        FROM warehouse_document_items
        WHERE document_id IN (${Prisma.join(documentIds)})
        GROUP BY document_id
      `,
    ]);
  const quantityByDocumentId = new Map(quantityGroups.map((row) => [row.documentId, Number(row._sum.quantity ?? 0)]));
  const valueByDocumentId = new Map(valueGroups.map((row) => [row.documentId, Number(row.totalValue ?? 0)]));
  const data = documents.map((document) => ({
    ...document,
    itemsCount: document._count.items,
    totalQuantity: quantityByDocumentId.get(document.id) ?? 0,
    totalValue: valueByDocumentId.get(document.id) ?? 0,
  }));

  return {
    data,
    total,
    page,
    limit,
    totalPages: Math.ceil(total / limit),
    summary: {
      stockWarningCount,
      confirmedThisMonth,
      autoWzFromOrders,
    },
  };
}

export async function getDocumentById(id: string) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const document = await prisma.warehouseDocument.findFirst({
    where,
    include: documentDetailInclude,
  });

  return withAuditUsers(document);
}

export async function createDocument(input: CreateDocumentInput) {
  const tenantId = getTenantId();
  if (!tenantId) throw new Error('Brak kontekstu tenanta');

  const preparedItems = await prepareDocumentItems(tenantId, input.items, true, input.type);
  const context = getTenantContext();
  const documentDate = input.date ? parseDateInput(input.date) : new Date();

  return prisma.$transaction(async (tx) => {
    const number = await generateDocumentNumber(tx, tenantId, input.type, documentDate);

    return tx.warehouseDocument.create({
      data: {
        tenantId,
        number,
        type: input.type,
        status: 'DRAFT',
        date: documentDate,
        description: input.description,
        orderId: input.orderId,
        createdByUserId: context?.userId,
        isAutoGenerated: input.isAutoGenerated ?? false,
        metadataJson: input.metadataJson,
        items: {
          create: preparedItems.map((item) => ({
            productId: item.productId,
            quantity: item.quantity,
            systemQuantity: item.systemQuantity ?? null,
            barcodeId: item.barcodeId,
            scannedEan: item.scannedEan,
            baseQuantity: item.baseQuantity,
            quantityMultiplier: item.quantityMultiplier,
            unitPrice: item.unitPrice,
            notes: item.notes,
            reservationId: item.reservationId,
          })),
        },
      },
      include: documentDetailInclude,
    });
  });
}

function metadataRecord(value: Prisma.JsonValue | null | undefined) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
  return value as Record<string, unknown>;
}

function numericQuantity(value: unknown) {
  const number = Number(value ?? 0);
  return Number.isFinite(number) ? number : 0;
}

function addQuantity(map: Map<string, number>, productId: string, quantity: unknown) {
  map.set(productId, (map.get(productId) ?? 0) + numericQuantity(quantity));
}

function formatDocumentQuantity(value: number) {
  return new Intl.NumberFormat('pl-PL', { maximumFractionDigits: 3 }).format(value);
}

function metadataString(value: Prisma.JsonValue | null | undefined, key: string) {
  const record = metadataRecord(value);
  const item = record[key];
  return typeof item === 'string' && item.trim() ? item.trim() : null;
}

function numberFromDecimal(value: Prisma.Decimal | number | string | null | undefined) {
  if (value === null || value === undefined) return 0;
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : 0;
}

function slugify(value: string) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'dostawca';
}

function todayFileDate() {
  return new Date().toISOString().slice(0, 10);
}

function formatCsvQuantity(value: number) {
  const rounded = Math.round(value * 1000) / 1000;
  if (Number.isInteger(rounded)) return String(rounded);
  return String(rounded).replace('.', ',');
}

function csvEscape(value: string | number | null | undefined, separator: ',' | ';') {
  const text = value === null || value === undefined ? '' : String(value);
  if (!text.includes(separator) && !text.includes('"') && !text.includes('\n') && !text.includes('\r')) return text;
  return `"${text.replace(/"/g, '""')}"`;
}

function normalizeCsvUnit(value: string | null | undefined, template: WholesaleOrderCsvTemplate) {
  const unit = value?.trim() || 'szt';
  if (template === 'GODAN' && /^szt\.?$/i.test(unit)) return 'szt.';
  return unit;
}

type WholesaleOrderCsvTemplate = 'GODAN' | 'PARTYDECO' | 'GENERIC';

type WholesaleOrderCsvRow = {
  code: string;
  quantity: number;
  unit: string;
  providerPreset: WholesaleOrderCsvTemplate | null;
};

function providerPresetFromConfig(configJson: Prisma.JsonValue | null | undefined): WholesaleOrderCsvTemplate | null {
  const config = metadataRecord(configJson);
  const preset = typeof config.preset === 'string' ? config.preset.toUpperCase() : '';
  if (preset === 'GODAN' || preset === 'PARTYDECO') return preset;
  return null;
}

function detectWholesaleOrderCsvTemplate(providerName: string | null, rows: WholesaleOrderCsvRow[]): WholesaleOrderCsvTemplate {
  const presets = rows.map((row) => row.providerPreset).filter(Boolean);
  if (presets.includes('PARTYDECO')) return 'PARTYDECO';
  if (presets.includes('GODAN')) return 'GODAN';

  const normalizedName = (providerName ?? '').toLowerCase();
  if (normalizedName.includes('partydeco')) return 'PARTYDECO';
  if (normalizedName.includes('godan')) return 'GODAN';

  return 'GENERIC';
}

function pickWholesaleMappingForProvider(item: any, providerId: string | null) {
  const mappings = Array.isArray(item.product?.wholesaleMappings)
    ? item.product.wholesaleMappings
    : [];
  if (mappings.length === 0) return null;
  if (!providerId) return mappings[0];
  return mappings.find((mapping: any) => mapping.providerId === providerId) ?? mappings[0];
}

function buildWholesaleOrderCsv(documents: any[]): Omit<WholesaleOrderCsvExportResult, 'confirmedDocuments' | 'document' | 'documents'> {
  const firstDocument = documents[0];
  const firstMetadata = firstDocument ? firstDocument.metadataJson as Prisma.JsonValue | null : null;
  const providerId = metadataString(firstMetadata, 'providerId');
  let providerName = metadataString(firstMetadata, 'providerName');
  const rows: WholesaleOrderCsvRow[] = [];

  for (const document of documents) {
    const documentProviderId = metadataString(document.metadataJson as Prisma.JsonValue | null, 'providerId') ?? providerId;
    const documentProviderName = metadataString(document.metadataJson as Prisma.JsonValue | null, 'providerName');
    if (!providerName && documentProviderName) providerName = documentProviderName;

    for (const item of document.items ?? []) {
      const mapping = pickWholesaleMappingForProvider(item, documentProviderId);
      const mappingProviderName = typeof mapping?.provider?.name === 'string' ? mapping.provider.name : null;
      if (!providerName && mappingProviderName) providerName = mappingProviderName;

      const code = [
        mapping?.externalSku,
        mapping?.externalEan,
        item.scannedEan,
        item.product?.sku,
      ].find((value) => typeof value === 'string' && value.trim())?.trim();
      if (!code) continue;

      rows.push({
        code,
        quantity: numberFromDecimal(item.quantity),
        unit: item.product?.unit ?? 'szt',
        providerPreset: providerPresetFromConfig(mapping?.provider?.configJson as Prisma.JsonValue | null | undefined),
      });
    }
  }

  if (rows.length === 0) throw new Error('Brak pozycji z kodem dostawcy do eksportu CSV');

  const template = detectWholesaleOrderCsvTemplate(providerName, rows);
  const separator: ',' | ';' = template === 'GODAN' ? ',' : ';';
  const aggregated = new Map<string, WholesaleOrderCsvRow>();

  for (const row of rows) {
    const unit = normalizeCsvUnit(row.unit, template);
    const key = template === 'GODAN' ? `${row.code}|${unit}` : row.code;
    const existing = aggregated.get(key);
    if (existing) {
      existing.quantity += row.quantity;
    } else {
      aggregated.set(key, { ...row, unit });
    }
  }

  const exportRows = Array.from(aggregated.values())
    .filter((row) => row.quantity > 0)
    .sort((a, b) => a.code.localeCompare(b.code, 'pl'));
  if (exportRows.length === 0) throw new Error('Brak pozycji z dodatnią ilością do eksportu CSV');

  const csvRows = template === 'GODAN'
    ? [
        ['Kod produktu/Ean', 'Ilość', 'Jednostka miary'],
        ...exportRows.map((row) => [row.code, formatCsvQuantity(row.quantity), row.unit]),
      ]
    : [
        ['code', 'count'],
        ...exportRows.map((row) => [row.code, formatCsvQuantity(row.quantity)]),
      ];
  const content = `${csvRows.map((row) => row.map((cell) => csvEscape(cell, separator)).join(separator)).join('\n')}\n`;
  const documentPart = documents.length === 1 ? `-${slugify(documents[0].number)}` : '';

  return {
    providerId,
    providerName,
    filename: `zamowienie-${slugify(providerName ?? 'dostawca')}${documentPart}-${todayFileDate()}.csv`,
    content,
    mimeType: 'text/csv;charset=utf-8',
    rows: exportRows.length,
  };
}

export async function exportWholesaleOrderCsv(id: string): Promise<WholesaleOrderCsvExportResult> {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const document = await prisma.warehouseDocument.findFirst({
    where,
    include: documentDetailInclude,
  });
  if (!document) throw new Error('Dokument nie znaleziony');
  if (document.type !== 'ZH') throw new Error('CSV zamówienia można wygenerować tylko dla dokumentu ZH');
  if (document.status === 'CANCELLED') throw new Error('Nie można wygenerować CSV z anulowanego zamówienia hurtowego');
  if (document.items.length === 0) throw new Error('Dokument ZH nie ma żadnych pozycji');

  const csv = buildWholesaleOrderCsv([document]);
  let confirmedDocuments = 0;
  if (document.status === 'DRAFT') {
    await confirmDocument(document.id);
    confirmedDocuments = 1;
  }

  return {
    ...csv,
    confirmedDocuments,
    document: await getDocumentById(document.id),
  };
}

export async function exportWholesaleOrdersForProviderCsv(providerId: string): Promise<WholesaleOrderCsvExportResult> {
  const tenantId = getTenantId();
  if (!tenantId) throw new Error('Brak kontekstu tenanta');

  const documents = await prisma.warehouseDocument.findMany({
    where: {
      tenantId,
      type: 'ZH',
      status: 'DRAFT',
    },
    include: documentDetailInclude,
    orderBy: [{ date: 'asc' }, { createdAt: 'asc' }],
  });
  const providerDocuments = documents.filter((document) => metadataString(document.metadataJson, 'providerId') === providerId);
  if (providerDocuments.length === 0) throw new Error('Brak roboczych dokumentów ZH do eksportu dla tego dostawcy');

  const csv = buildWholesaleOrderCsv(providerDocuments);
  const documentIds = providerDocuments.map((document) => document.id);
  for (const documentId of documentIds) {
    await confirmDocument(documentId);
  }

  const confirmedDocuments = (await Promise.all(documentIds.map((documentId) => getDocumentById(documentId))))
    .filter((document): document is NonNullable<typeof document> => Boolean(document));

  return {
    ...csv,
    confirmedDocuments: documentIds.length,
    documents: confirmedDocuments,
  };
}

export async function createPzFromWholesaleOrder(id: string, input: CreatePzFromWholesaleOrderInput = {}): Promise<CreatePzFromWholesaleOrderResult> {
  const tenantId = getTenantId();
  const context = getTenantContext();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const sourceDocument = await prisma.warehouseDocument.findFirst({
    where,
    include: documentDetailInclude,
  });
  if (!sourceDocument) throw new Error('Dokument nie znaleziony');
  if (sourceDocument.type !== 'ZH') throw new Error('PZ można utworzyć tylko z dokumentu ZH');
  if (sourceDocument.status === 'CANCELLED') throw new Error('Nie można utworzyć PZ z anulowanego zamówienia hurtowego');
  if (sourceDocument.items.length === 0) throw new Error('Dokument ZH nie ma żadnych pozycji');

  const sourceMetadata = metadataRecord(sourceDocument.metadataJson);
  const existingPzId = typeof sourceMetadata.convertedToPzDocumentId === 'string'
    ? sourceMetadata.convertedToPzDocumentId
    : null;
  if (existingPzId) {
    const existing = await getDocumentById(existingPzId);
    if (existing && existing.status !== 'CANCELLED') {
      if (sourceDocument.status === 'DRAFT') {
        await prisma.warehouseDocument.update({
          where: { id: sourceDocument.id },
          data: {
            status: 'CONFIRMED',
            confirmedAt: new Date(),
            confirmedByUserId: context?.userId,
          },
        });
      }

      return {
        document: existing,
        created: false,
        skippedReason: `PZ dla ${sourceDocument.number} już istnieje`,
      };
    }
  }

  const documentDate = new Date();
  const shouldConfirmPz = input.saveAsDraft !== true;
  const usesDeliveryCheckItems = Array.isArray(input.items);
  const sourceItemByProductId = new Map(sourceDocument.items.map((item) => [item.productId, item]));
  const sourceQuantityByProductId = new Map<string, number>();
  for (const item of sourceDocument.items) {
    addQuantity(sourceQuantityByProductId, item.productId, item.quantity);
  }

  const pzItems: PreparedDocumentItem[] = usesDeliveryCheckItems
    ? await prepareDocumentItems(sourceDocument.tenantId, input.items ?? [], true, 'PZ')
    : sourceDocument.items.map((item) => ({
        productId: item.productId,
        quantity: numericQuantity(item.quantity),
        unitPrice: item.unitPrice === null || item.unitPrice === undefined ? undefined : Number(item.unitPrice),
        notes: item.notes ?? `Przyjęcie z ${sourceDocument.number}`,
      }));

  if (pzItems.length === 0) {
    throw new Error(usesDeliveryCheckItems ? 'Brak zeskanowanych pozycji do utworzenia PZ' : 'Dokument ZH nie ma żadnych pozycji');
  }

  const acceptedQuantityByProductId = new Map<string, number>();
  for (const item of pzItems) {
    addQuantity(acceptedQuantityByProductId, item.productId, item.quantity);
  }

  const deliveryCheckSummary = usesDeliveryCheckItems
    ? {
        totalExpected: Array.from(sourceQuantityByProductId.values()).reduce((sum, quantity) => sum + quantity, 0),
        totalAccepted: Array.from(acceptedQuantityByProductId.values()).reduce((sum, quantity) => sum + quantity, 0),
        missingItems: Array.from(sourceQuantityByProductId.entries())
          .map(([productId, expected]) => {
            const accepted = acceptedQuantityByProductId.get(productId) ?? 0;
            return {
              productId,
              sku: sourceItemByProductId.get(productId)?.product?.sku,
              name: sourceItemByProductId.get(productId)?.product?.name,
              expected,
              accepted,
              missing: Math.max(0, expected - accepted),
            };
          })
          .filter((item) => item.missing > 0),
        overageItems: Array.from(acceptedQuantityByProductId.entries())
          .map(([productId, accepted]) => {
            const expected = sourceQuantityByProductId.get(productId) ?? 0;
            return {
              productId,
              sku: sourceItemByProductId.get(productId)?.product?.sku,
              name: sourceItemByProductId.get(productId)?.product?.name,
              expected,
              accepted,
              overage: Math.max(0, accepted - expected),
              outsideOrder: !sourceQuantityByProductId.has(productId),
            };
          })
          .filter((item) => item.overage > 0),
      }
    : undefined;

  const createdDocument = await prisma.$transaction(async (tx) => {
    const number = await generateDocumentNumber(tx, sourceDocument.tenantId, 'PZ', documentDate);
    const metadataJson = {
      source: 'WHOLESALE_ORDER',
      wholesaleOrderDocumentId: sourceDocument.id,
      wholesaleOrderNumber: sourceDocument.number,
      providerId: sourceMetadata.providerId,
      providerName: sourceMetadata.providerName,
      createdFromDeliveryCheck: usesDeliveryCheckItems,
      savedAsDraft: !shouldConfirmPz,
      deliveryCheckSummary,
    };

    const pz = await tx.warehouseDocument.create({
      data: {
        tenantId: sourceDocument.tenantId,
        number,
        type: 'PZ',
        status: shouldConfirmPz ? 'CONFIRMED' : 'DRAFT',
        date: documentDate,
        description: usesDeliveryCheckItems
          ? `PZ według kontroli dostawy ${sourceDocument.number}`
          : `PZ do zamówienia hurtowego ${sourceDocument.number}`,
        createdByUserId: context?.userId,
        confirmedAt: shouldConfirmPz ? new Date() : undefined,
        confirmedByUserId: shouldConfirmPz ? context?.userId : undefined,
        metadataJson: JSON.parse(JSON.stringify(metadataJson)),
        items: {
          create: pzItems.map((item) => {
            const sourceItem = sourceItemByProductId.get(item.productId);
            const expected = sourceQuantityByProductId.get(item.productId);
            const accepted = acceptedQuantityByProductId.get(item.productId) ?? numericQuantity(item.quantity);
            const deliveryCheckNote = usesDeliveryCheckItems && expected !== undefined && accepted < expected
              ? `Kontrola dostawy: przyjęto ${formatDocumentQuantity(accepted)} z ${formatDocumentQuantity(expected)}, brak ${formatDocumentQuantity(expected - accepted)}`
              : usesDeliveryCheckItems && expected !== undefined && accepted > expected
                ? `Kontrola dostawy: przyjęto ${formatDocumentQuantity(accepted)} z ${formatDocumentQuantity(expected)}, nadwyżka ${formatDocumentQuantity(accepted - expected)}`
                : usesDeliveryCheckItems && expected === undefined
                  ? `Kontrola dostawy: produkt poza ${sourceDocument.number}`
                  : undefined;
            return {
              productId: item.productId,
              quantity: item.quantity,
              barcodeId: item.barcodeId,
              scannedEan: item.scannedEan,
              baseQuantity: item.baseQuantity,
              quantityMultiplier: item.quantityMultiplier,
              unitPrice: item.unitPrice ?? sourceItem?.unitPrice ?? null,
              notes: item.notes ?? deliveryCheckNote ?? sourceItem?.notes ?? `Przyjęcie z ${sourceDocument.number}`,
            };
          }),
        },
      },
      include: documentDetailInclude,
    });

    if (shouldConfirmPz) {
      await applyIncomingPurchaseCosts(tx, 'PZ', pz.items);
      await applyStockDeltas(tx, 'PZ', pz.items);
    }

    await tx.warehouseDocument.update({
      where: { id: sourceDocument.id },
      data: {
        ...(sourceDocument.status === 'DRAFT'
          ? {
              status: 'CONFIRMED' as const,
              confirmedAt: new Date(),
              confirmedByUserId: context?.userId,
            }
          : {}),
        metadataJson: JSON.parse(JSON.stringify({
          ...sourceMetadata,
          convertedToPzDocumentId: pz.id,
          convertedToPzDocumentNumber: pz.number,
          convertedAt: new Date().toISOString(),
        })),
      },
    });

    return pz;
  });

  if (shouldConfirmPz) {
    const affectedProductIds = Array.from(new Set(createdDocument.items.map((item) => item.productId)));
    await reallocateWholesaleBackordersForProducts(sourceDocument.tenantId, affectedProductIds);
    await syncStockForProducts(affectedProductIds, 'DOCUMENT_CONFIRM', createdDocument.id);
  }

  return {
    document: await withAuditUsers(createdDocument),
    created: true,
  };
}

export async function createWzForOrder(orderId: string, input: CreateWzForOrderInput = {}): Promise<CreateWzForOrderResult> {
  const contextTenantId = getTenantId();
  const order = await prisma.order.findFirst({
    where: {
      id: orderId,
      ...(contextTenantId ? { shop: { tenantId: contextTenantId } } : {}),
    },
    include: {
      shop: true,
      items: true,
    },
  });

  if (!order) throw new Error('Zamówienie nie znalezione');

  const existingDocument = await prisma.warehouseDocument.findFirst({
    where: {
      tenantId: order.shop.tenantId,
      orderId,
      type: 'WZ',
      status: { not: 'CANCELLED' },
    },
    include: documentDetailInclude,
  });

  if (existingDocument) {
    return {
      document: await withAuditUsers(existingDocument),
      created: false,
      skippedReason: 'WZ dla tego zamówienia już istnieje',
    };
  }

  if (order.items.length === 0) {
    return { document: null, created: false, skippedReason: 'Zamówienie nie ma pozycji' };
  }

  let activeReservations = await prisma.warehouseReservation.findMany({
    where: {
      tenantId: order.shop.tenantId,
      orderId: order.id,
      status: 'ACTIVE',
    },
    include: {
      warehouseProduct: true,
      orderItem: true,
    },
    orderBy: { createdAt: 'asc' },
  });

  let reservationResult: Awaited<ReturnType<typeof reserveOrder>> | null = null;
  if (activeReservations.length === 0) {
    reservationResult = await reserveOrder(order.id);
    activeReservations = await prisma.warehouseReservation.findMany({
      where: {
        tenantId: order.shop.tenantId,
        orderId: order.id,
        status: 'ACTIVE',
      },
      include: {
        warehouseProduct: true,
        orderItem: true,
      },
      orderBy: { createdAt: 'asc' },
    });
  }

  if (activeReservations.length === 0) {
    return { document: null, created: false, skippedReason: 'Brak aktywnych rezerwacji do wydania WZ' };
  }

  const stockWarning = Boolean(
    reservationResult && (reservationResult.partial > 0 || reservationResult.missingMapping > 0 || reservationResult.missingStock > 0),
  );
  const settings = await getWarehouseSettings(order.shop.tenantId);
  const shippingInfo = extractOrderShippingInfo(order.payloadJson, order.currency);
  const shippingDescription = buildShippingInfoDescription(shippingInfo);
  const metadata: Record<string, unknown> = {};
  if (stockWarning) {
    metadata.stockWarning = true;
    metadata.reservationIssues = JSON.parse(JSON.stringify(reservationResult?.issues ?? []));
    metadata.autoConfirmBlockedByStockWarning = true;
  }
  if (shippingInfo) {
    metadata.shipping = shippingInfo;
  }
  const shouldAutoConfirm = input.saveAsDraft !== true && (input.forceConfirm === true || settings.autoConfirmWzOnOrder) && !stockWarning;

  const document = await prisma.$transaction(async (tx) => {
    const documentDate = new Date();
    const number = await generateDocumentNumber(tx, order.shop.tenantId, 'WZ', documentDate);

    const createdDocument = await tx.warehouseDocument.create({
      data: {
        tenantId: order.shop.tenantId,
        number,
        type: 'WZ',
        status: shouldAutoConfirm ? 'CONFIRMED' : 'DRAFT',
        date: documentDate,
        description: [
          `WZ automatyczne dla zamówienia ${order.orderReference}`,
          shippingDescription,
        ].filter(Boolean).join('. '),
        orderId: order.id,
        isAutoGenerated: true,
        metadataJson: Object.keys(metadata).length > 0 ? JSON.parse(JSON.stringify(metadata)) : undefined,
        confirmedAt: shouldAutoConfirm ? new Date() : undefined,
        items: {
          create: activeReservations.map((reservation) => ({
            productId: reservation.warehouseProductId,
            quantity: reservation.quantity,
            reservationId: reservation.id,
            notes: `Zamówienie ${order.orderReference}`,
          })),
        },
      },
      include: documentDetailInclude,
    });

    if (shouldAutoConfirm) {
      await consumeDocumentReservations(tx, createdDocument.items);
    }

    return createdDocument;
  });

  if (shouldAutoConfirm) {
    await syncStockForProducts(
      Array.from(new Set(document.items.map((item) => item.productId))),
      'DOCUMENT_CONFIRM',
      document.id,
    );
  }

  return { document: await withAuditUsers(document), created: true };
}

export async function updateDocument(id: string, input: UpdateDocumentInput) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const data: any = {};
  if (input.date !== undefined) data.date = parseDateInput(input.date);
  if (input.description !== undefined) data.description = input.description;
  if (input.orderId !== undefined) data.orderId = input.orderId;

  let preparedItems: PreparedDocumentItem[] | null = null;
  if (input.items !== undefined) {
    preparedItems = await prepareDocumentItems(tenantId ?? doc.tenantId, input.items, true, doc.type as DocumentType);
  }

  return prisma.$transaction(async (tx) => {
    if (preparedItems) {
      await tx.warehouseDocumentItem.deleteMany({ where: { documentId: id } });
      if (preparedItems.length > 0) {
        await tx.warehouseDocumentItem.createMany({
          data: preparedItems.map((item) => ({
            documentId: id,
            productId: item.productId,
            quantity: item.quantity,
            systemQuantity: item.systemQuantity ?? null,
            barcodeId: item.barcodeId,
            scannedEan: item.scannedEan,
            baseQuantity: item.baseQuantity,
            quantityMultiplier: item.quantityMultiplier,
            unitPrice: item.unitPrice,
            notes: item.notes,
            reservationId: item.reservationId,
          })),
        });
      }
    }

    return tx.warehouseDocument.update({
      where: { id },
      data,
      include: documentDetailInclude,
    });
  });
}

export async function mergeDocumentItem(documentId: string, input: DocumentItemInput) {
  const tenantId = getTenantId();
  const where: any = { id: documentId };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const [preparedItem] = await prepareDocumentItems(tenantId ?? doc.tenantId, [input], true, doc.type as DocumentType);
  if (!preparedItem) throw new Error('Pozycja dokumentu jest wymagana');

  const isInventory = doc.type === 'INW';

  const updatedDocument = await prisma.$transaction(async (tx) => {
    const existingItem = await tx.warehouseDocumentItem.findFirst({
      where: {
        documentId,
        productId: preparedItem.productId,
        ...(isInventory ? {} : { barcodeId: preparedItem.barcodeId ?? null }),
      },
    });

    if (existingItem) {
      if (isInventory) {
        await tx.warehouseDocumentItem.update({
          where: { id: existingItem.id },
          data: {
            quantity: preparedItem.quantity,
            systemQuantity: preparedItem.systemQuantity ?? null,
            scannedEan: preparedItem.scannedEan ?? existingItem.scannedEan,
            notes: preparedItem.notes ?? existingItem.notes,
          },
        });
      } else {
        await tx.warehouseDocumentItem.update({
          where: { id: existingItem.id },
          data: {
            quantity: new Prisma.Decimal(existingItem.quantity).plus(preparedItem.quantity),
            baseQuantity:
              existingItem.baseQuantity || preparedItem.baseQuantity
                ? new Prisma.Decimal(existingItem.baseQuantity ?? 0).plus(preparedItem.baseQuantity ?? 0)
                : null,
            quantityMultiplier: existingItem.quantityMultiplier ?? preparedItem.quantityMultiplier,
            scannedEan: existingItem.scannedEan ?? preparedItem.scannedEan,
            unitPrice: existingItem.unitPrice ?? preparedItem.unitPrice,
            notes: existingItem.notes || preparedItem.notes,
          },
        });
      }
    } else {
      await tx.warehouseDocumentItem.create({
        data: {
          documentId,
          productId: preparedItem.productId,
          quantity: preparedItem.quantity,
          systemQuantity: preparedItem.systemQuantity ?? null,
          barcodeId: preparedItem.barcodeId,
          scannedEan: preparedItem.scannedEan,
          baseQuantity: preparedItem.baseQuantity,
          quantityMultiplier: preparedItem.quantityMultiplier,
          unitPrice: preparedItem.unitPrice,
          notes: preparedItem.notes,
          reservationId: preparedItem.reservationId,
        },
      });
    }

    return tx.warehouseDocument.findUnique({
      where: { id: documentId },
      include: documentDetailInclude,
    });
  });

  return updatedDocument;
}

export async function updateDocumentItem(documentId: string, itemId: string, input: UpdateDocumentItemInput) {
  const tenantId = getTenantId();
  const documentWhere: any = { id: documentId };
  if (tenantId) documentWhere.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where: documentWhere });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const item = await prisma.warehouseDocumentItem.findFirst({ where: { id: itemId, documentId } });
  if (!item) throw new Error('Pozycja dokumentu nie znaleziona');

  const isInventory = doc.type === 'INW';

  const data: Prisma.WarehouseDocumentItemUpdateInput = {};
  if (input.quantity !== undefined) {
    if (isInventory) {
      if (input.quantity < 0) throw new Error('Stan policzony nie może być ujemny');
    } else if (input.quantity <= 0) {
      throw new Error('Ilość pozycji musi być większa od 0');
    }
    data.quantity = input.quantity;
  }
  if (input.systemQuantity !== undefined) {
    if (!isInventory) throw new Error('Stan systemowy można aktualizować tylko w dokumencie INW');
    if (input.systemQuantity !== null && input.systemQuantity < 0) throw new Error('Stan systemowy nie może być ujemny');
    data.systemQuantity = input.systemQuantity;
  }
  if (input.baseQuantity !== undefined) {
    if (input.baseQuantity !== null && input.baseQuantity <= 0) throw new Error('Ilość bazowa musi być większa od 0');
    data.baseQuantity = input.baseQuantity;
  }
  if (input.quantityMultiplier !== undefined) {
    if (input.quantityMultiplier !== null && input.quantityMultiplier <= 0) throw new Error('Przelicznik EAN musi być większy od 0');
    data.quantityMultiplier = input.quantityMultiplier;
  }
  if (input.unitPrice !== undefined) {
    if (input.unitPrice !== null && input.unitPrice < 0) throw new Error('Cena pozycji nie może być ujemna');
    data.unitPrice = input.unitPrice;
  }
  if (input.notes !== undefined) data.notes = input.notes;

  await prisma.warehouseDocumentItem.update({
    where: { id: itemId },
    data,
  });

  return prisma.warehouseDocument.findUnique({
    where: { id: documentId },
    include: documentDetailInclude,
  });
}

export async function deleteDocumentItem(documentId: string, itemId: string) {
  const tenantId = getTenantId();
  const documentWhere: any = { id: documentId };
  if (tenantId) documentWhere.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where: documentWhere });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const item = await prisma.warehouseDocumentItem.findFirst({ where: { id: itemId, documentId } });
  if (!item) throw new Error('Pozycja dokumentu nie znaleziona');

  await prisma.warehouseDocumentItem.delete({ where: { id: itemId } });

  return prisma.warehouseDocument.findUnique({
    where: { id: documentId },
    include: documentDetailInclude,
  });
}

export async function confirmDocument(id: string) {
  const tenantId = getTenantId();
  const context = getTenantContext();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({
    where,
    include: { items: { include: { product: true } } },
  });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Tylko dokumenty DRAFT można zatwierdzić');

  if (doc.items.length === 0) throw new Error('Dokument nie ma żadnych pozycji');

  await assertCanConfirmWithoutNegativeStock(doc.tenantId, doc.type, doc.items);

  const confirmedDocument = await prisma.$transaction(async (tx) => {
    await applyIncomingPurchaseCosts(tx, doc.type, doc.items);
    await applyStockDeltas(tx, doc.type, doc.items);
    await consumeDocumentReservations(tx, doc.items);

    return tx.warehouseDocument.update({
      where: { id },
      data: {
        status: 'CONFIRMED',
        confirmedAt: new Date(),
        confirmedByUserId: context?.userId,
      },
        include: documentDetailInclude,
    });
  });

  const affectedProductIds = Array.from(new Set(doc.items.map((item) => item.productId)));
  if (doc.type === 'PZ') {
    await reallocateWholesaleBackordersForProducts(doc.tenantId, affectedProductIds);
  }

  await syncStockForProducts(
    affectedProductIds,
    'DOCUMENT_CONFIRM',
    id,
  );

  return confirmedDocument;
}

async function reallocateWholesaleBackordersForProducts(tenantId: string, productIds: string[]) {
  const uniqueProductIds = Array.from(new Set(productIds.filter(Boolean)));
  if (uniqueProductIds.length === 0) return;

  const reservations = await prisma.warehouseReservation.findMany({
    where: {
      tenantId,
      status: 'ACTIVE',
      source: 'WHOLESALE_BACKORDER',
      warehouseProductId: { in: uniqueProductIds },
      order: {
        operationalStatus: { in: STOCK_RESERVATION_ORDER_OPERATIONAL_STATUSES },
      },
    },
    select: { orderId: true },
  });

  const orderIds = Array.from(new Set(reservations.map((reservation) => reservation.orderId)));
  for (const orderId of orderIds) {
    await reserveOrder(orderId);
  }
}

async function assertCanConfirmWithoutNegativeStock(
  tenantId: string,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; systemQuantity?: Prisma.Decimal | null; reservationId?: string | null; product: { name: string; unit: string } }>,
) {
  if (type === 'INW') {
    for (const item of items) {
      if (Number(item.quantity) < 0) {
        throw new Error(`Stan policzony produktu "${item.product.name}" nie może być ujemny`);
      }
    }
    return;
  }

  if (!['WZ', 'RW'].includes(type)) return;

  const settings = await getWarehouseSettings(tenantId);
  if (settings.allowNegativeStock) return;

  const requestedByProduct = new Map<string, { quantity: number; name: string; unit: string }>();

  for (const item of items) {
    if (type === 'WZ' && item.reservationId) continue;

    const existing = requestedByProduct.get(item.productId);
    const quantity = Number(item.quantity);

    if (existing) {
      existing.quantity += quantity;
    } else {
      requestedByProduct.set(item.productId, {
        quantity,
        name: item.product.name,
        unit: item.product.unit,
      });
    }
  }

  if (requestedByProduct.size === 0) return;

  const products = await prisma.warehouseProduct.findMany({
    where: { tenantId, id: { in: Array.from(requestedByProduct.keys()) } },
    select: { id: true, currentStock: true },
  });
  const stockByProductId = new Map(products.map((product) => [product.id, Number(product.currentStock)]));

  for (const [productId, requested] of requestedByProduct) {
    const stock = stockByProductId.get(productId) ?? 0;
    const requestedQuantity = requested.quantity;
    const nextStock = stock - requestedQuantity;

    if (nextStock < 0) {
      throw new Error(
        `Niewystarczający stan produktu "${requested.name}": dostępne ${stock} ${requested.unit}, wymagane ${requestedQuantity} ${requested.unit}`,
      );
    }
  }
}

async function getWarehouseSettings(tenantId: string) {
  const tenant = await prisma.tenant.findUnique({
    where: { id: tenantId },
    select: { limitsJson: true },
  });

  const limits = tenant?.limitsJson as any;
  return {
    allowNegativeStock: limits?.warehouse?.allowNegativeStock === true,
    autoCreateWzOnOrder: limits?.warehouse?.autoCreateWzOnOrder !== false,
    autoConfirmWzOnOrder: limits?.warehouse?.autoConfirmWzOnOrder === true,
  };
}

export async function shouldAutoCreateWzForTenant(tenantId: string) {
  const settings = await getWarehouseSettings(tenantId);
  return settings.autoCreateWzOnOrder;
}

export async function cancelDocument(id: string, input: CancelDocumentInput = {}) {
  const tenantId = getTenantId();
  const context = getTenantContext();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({
    where,
    include: { items: true },
  });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status === 'CANCELLED') throw new Error('Dokument jest już anulowany');

  const cancelledDocument = await prisma.$transaction(async (tx) => {
    if (doc.status === 'CONFIRMED') {
      await applyStockDeltas(tx, doc.type, doc.items, true);
      await releaseDocumentReservations(tx, doc.items);
    }

    return tx.warehouseDocument.update({
      where: { id },
      data: {
        status: 'CANCELLED',
        cancelledAt: new Date(),
        cancelledByUserId: context?.userId,
        cancelReason: input.reason,
      },
      include: documentDetailInclude,
    });
  });

  if (doc.status === 'CONFIRMED') {
    await syncStockForProducts(
      doc.items.map((item) => item.productId),
      'DOCUMENT_CANCEL',
      id,
    );
  }

  return cancelledDocument;
}

export async function deleteDocument(id: string) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można usunąć tylko dokumenty w statusie DRAFT');

  return prisma.warehouseDocument.delete({ where: { id } });
}

async function prepareDocumentItems(
  tenantId: string,
  items: DocumentItemInput[],
  requireActiveProduct: boolean,
  type?: DocumentType,
): Promise<PreparedDocumentItem[]> {
  const isInventory = type === 'INW';
  const preparedItems: PreparedDocumentItem[] = [];
  const productIds = Array.from(new Set(items.map((item) => item.productId).filter(Boolean)));
  const barcodeIds = Array.from(new Set(items.map((item) => item.barcodeId).filter(Boolean) as string[]));

  if (isInventory) {
    const seen = new Set<string>();
    for (const item of items) {
      if (seen.has(item.productId)) {
        throw new Error('W dokumencie INW każdy produkt może wystąpić tylko raz');
      }
      seen.add(item.productId);
    }
  }

  const productSelect = isInventory
    ? { id: true, name: true, isActive: true, currentStock: true }
    : { id: true, name: true, isActive: true };

  const [products, barcodes] = await Promise.all([
    prisma.warehouseProduct.findMany({
      where: { id: { in: productIds }, tenantId },
      select: productSelect,
    }),
    barcodeIds.length > 0
      ? prisma.warehouseProductBarcode.findMany({
          where: { id: { in: barcodeIds }, tenantId },
          select: {
            id: true,
            warehouseProductId: true,
            ean: true,
            quantityMultiplier: true,
            isActive: true,
          },
        })
      : Promise.resolve([]),
  ]);

  const productById = new Map(products.map((product) => [product.id, product as typeof product & { currentStock?: Prisma.Decimal }]));
  const barcodeById = new Map(barcodes.map((barcode) => [barcode.id, barcode]));

  for (const item of items) {
    const product = productById.get(item.productId);
    if (!product) throw new Error(`Produkt ${item.productId} nie znaleziony`);
    if (requireActiveProduct && !product.isActive) throw new Error(`Produkt "${product.name}" jest nieaktywny`);

    let scannedEan = item.scannedEan?.trim() || undefined;
    let quantityMultiplier = item.quantityMultiplier;
    const barcodeId = item.barcodeId;

    if (barcodeId) {
      const barcode = barcodeById.get(barcodeId);
      if (!barcode) throw new Error(`Kod EAN ${barcodeId} nie znaleziony dla produktu "${product.name}"`);
      if (barcode.warehouseProductId !== item.productId) {
        throw new Error(`Kod EAN ${barcodeId} nie znaleziony dla produktu "${product.name}"`);
      }
      if (!barcode.isActive) throw new Error(`Kod EAN "${barcode.ean}" jest nieaktywny`);
      scannedEan = scannedEan ?? barcode.ean;
      quantityMultiplier = quantityMultiplier ?? Number(barcode.quantityMultiplier);
    }

    const minQuantity = isInventory ? 0 : 0; // próg dolny włącznie — INW dopuszcza 0
    const requireStrictPositive = !isInventory;

    const baseQuantity = item.baseQuantity ?? item.quantity;
    if (baseQuantity === undefined || (requireStrictPositive ? baseQuantity <= 0 : baseQuantity < minQuantity)) {
      throw new Error(isInventory ? 'Stan policzony nie może być ujemny' : 'Ilość pozycji musi być większa od 0');
    }

    quantityMultiplier = quantityMultiplier ?? 1;
    if (quantityMultiplier <= 0) throw new Error('Przelicznik EAN musi być większy od 0');

    const quantity = item.quantity ?? baseQuantity * quantityMultiplier;
    if (requireStrictPositive ? quantity <= 0 : quantity < minQuantity) {
      throw new Error(isInventory ? 'Stan policzony nie może być ujemny' : 'Ilość pozycji musi być większa od 0');
    }

    let systemQuantity: number | null | undefined;
    if (isInventory) {
      if (item.systemQuantity === null || item.systemQuantity === undefined) {
        systemQuantity = Number(product.currentStock ?? 0);
      } else {
        systemQuantity = Number(item.systemQuantity);
        if (!Number.isFinite(systemQuantity)) {
          throw new Error('Stan systemowy jest nieprawidłowy');
        }
      }
    }

    preparedItems.push({
      productId: item.productId,
      quantity,
      systemQuantity,
      barcodeId,
      scannedEan,
      baseQuantity,
      quantityMultiplier,
      unitPrice: item.unitPrice,
      notes: item.notes,
      reservationId: item.reservationId ?? null,
    });
  }

  return preparedItems;
}

async function applyStockDeltas(
  tx: Prisma.TransactionClient,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; systemQuantity?: Prisma.Decimal | null; reservationId?: string | null }>,
  reverse = false,
) {
  if (type === 'INW') {
    const deltas = new Map<string, Prisma.Decimal>();
    for (const item of items) {
      const counted = new Prisma.Decimal(item.quantity);
      const system = new Prisma.Decimal(item.systemQuantity ?? 0);
      const delta = reverse ? system.minus(counted) : counted.minus(system);
      deltas.set(item.productId, (deltas.get(item.productId) ?? new Prisma.Decimal(0)).plus(delta));
    }
    for (const [productId, delta] of deltas) {
      if (delta.equals(0)) continue;
      await tx.warehouseProduct.update({
        where: { id: productId },
        data: { currentStock: { increment: delta } },
      });
    }
    return;
  }

  const baseSign = getStockDeltaSign(type);
  if (baseSign === 0) return;

  const sign = reverse ? -baseSign : baseSign;
  const deltas = new Map<string, Prisma.Decimal>();

  for (const item of items) {
    if (type === 'WZ' && item.reservationId) continue;

    const current = deltas.get(item.productId) ?? new Prisma.Decimal(0);
    deltas.set(item.productId, current.plus(item.quantity.mul(sign)));
  }

  for (const [productId, delta] of deltas) {
    await tx.warehouseProduct.update({
      where: { id: productId },
      data: { currentStock: { increment: delta } },
    });
  }
}

async function applyIncomingPurchaseCosts(
  tx: Prisma.TransactionClient,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; unitPrice?: Prisma.Decimal | null }>,
) {
  if (type !== 'PZ') return;

  const incomingByProduct = new Map<string, { quantity: Prisma.Decimal; value: Prisma.Decimal }>();
  for (const item of items) {
    if (item.unitPrice === null || item.unitPrice === undefined) continue;
    const quantity = new Prisma.Decimal(item.quantity);
    if (quantity.lte(0)) continue;
    const value = quantity.mul(item.unitPrice);
    const current = incomingByProduct.get(item.productId) ?? {
      quantity: new Prisma.Decimal(0),
      value: new Prisma.Decimal(0),
    };
    incomingByProduct.set(item.productId, {
      quantity: current.quantity.plus(quantity),
      value: current.value.plus(value),
    });
  }

  for (const [productId, incoming] of incomingByProduct) {
    const product = await tx.warehouseProduct.findUnique({
      where: { id: productId },
      select: { currentStock: true, averagePurchaseCost: true, purchasePrice: true },
    });
    if (!product) continue;

    const currentStock = Prisma.Decimal.max(new Prisma.Decimal(product.currentStock), new Prisma.Decimal(0));
    const currentCost = new Prisma.Decimal(product.averagePurchaseCost ?? product.purchasePrice ?? 0);
    const nextStock = currentStock.plus(incoming.quantity);
    const nextCost = currentStock.gt(0) && currentCost.gt(0)
      ? currentStock.mul(currentCost).plus(incoming.value).div(nextStock)
      : incoming.value.div(incoming.quantity);

    await tx.warehouseProduct.update({
      where: { id: productId },
      data: { averagePurchaseCost: new Prisma.Decimal(nextCost.toFixed(2)) },
    });
  }
}

function getStockDeltaSign(type: DocumentType) {
  if (STOCK_INCOMING_TYPES.includes(type)) return 1;
  if (STOCK_OUTGOING_TYPES.includes(type)) return -1;
  return 0;
}

// ─── Numeracja dokumentów ─────────────────────────────────────────────────────

async function generateDocumentNumber(
  tx: Prisma.TransactionClient,
  tenantId: string,
  type: DocumentType,
  documentDate = new Date(),
): Promise<string> {
  const year = documentDate.getFullYear();
  const prefix = `${type}/${year}/`;
  const lockKey = `${tenantId}:${type}:${year}`;

  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${lockKey}))`;

  const rows = await tx.$queryRaw<Array<{ max: number | bigint | string | null }>>`
    SELECT COALESCE(MAX(CAST(split_part("number", '/', 3) AS INTEGER)), 0) AS max
    FROM "warehouse_documents"
    WHERE "tenant_id" = ${tenantId}
      AND "number" LIKE ${prefix + '%'}
      AND split_part("number", '/', 3) ~ '^[0-9]+$'
  `;
  const seq = Number(rows[0]?.max ?? 0) + 1;

  return `${prefix}${String(seq).padStart(3, '0')}`;
}
