import prisma from '../../lib/prisma';
import { Prisma } from '@prisma/client';
import { getTenantContext, getTenantId } from '../../lib/tenant-context';
import { syncStockForProducts } from '../stock/stock-sync.service';
import { consumeDocumentReservations, releaseDocumentReservations, reserveOrder } from './warehouse-reservations.service';
import { buildShippingInfoDescription, extractOrderShippingInfo } from '../orders/order-shipping-info.service';

// ─── Documents ───────────────────────────────────────────────────────────────

export type DocumentType = 'PZ' | 'PW' | 'WZ' | 'RW' | 'INW';
const STOCK_INCOMING_TYPES: DocumentType[] = ['PZ', 'PW'];
const STOCK_OUTGOING_TYPES: DocumentType[] = ['WZ', 'RW'];

export interface DocumentItemInput {
  productId: string;
  quantity?: number;
  /** Wymagany tylko dla INW: snapshot stanu systemowego z momentu wpisania pozycji. Jeśli null, serwis bierze bieżący `currentStock`. */
  systemQuantity?: number | null;
  barcodeId?: string;
  scannedEan?: string;
  baseQuantity?: number;
  quantityMultiplier?: number;
  unitPrice?: number;
  notes?: string;
  reservationId?: string | null;
}

export interface CreateDocumentInput {
  type: DocumentType;
  date?: string;
  description?: string;
  orderId?: string;
  isAutoGenerated?: boolean;
  metadataJson?: Prisma.InputJsonValue;
  items: DocumentItemInput[];
}

export interface UpdateDocumentInput {
  date?: string;
  description?: string;
  orderId?: string | null;
  items?: DocumentItemInput[];
}

export interface UpdateDocumentItemInput {
  quantity?: number;
  /** Tylko INW: aktualizacja snapshotu stanu systemowego (np. po wyborze "odśwież snapshot"). */
  systemQuantity?: number | null;
  baseQuantity?: number | null;
  quantityMultiplier?: number | null;
  unitPrice?: number | null;
  notes?: string | null;
}

export interface CancelDocumentInput {
  reason?: string;
}

export interface CreateWzForOrderResult {
  document: Awaited<ReturnType<typeof getDocumentById>>;
  created: boolean;
  skippedReason?: string;
}

export interface DocumentsQuery {
  page?: number;
  limit?: number;
  type?: DocumentType;
  status?: 'DRAFT' | 'CONFIRMED' | 'CANCELLED';
  dateFrom?: string;
  dateTo?: string;
}

interface PreparedDocumentItem {
  productId: string;
  quantity: number;
  systemQuantity?: number | null;
  barcodeId?: string;
  scannedEan?: string;
  baseQuantity?: number;
  quantityMultiplier?: number;
  unitPrice?: number;
  notes?: string;
  reservationId?: string | null;
}

export async function getDocuments(query: DocumentsQuery = {}) {
  const tenantId = getTenantId();
  const { page = 1, limit = 20, type, status, dateFrom, dateTo } = query;
  const skip = (page - 1) * limit;

  const where: any = {};
  if (tenantId) where.tenantId = tenantId;
  if (type) where.type = type;
  if (status) where.status = status;
  if (dateFrom || dateTo) {
    where.date = {};
    if (dateFrom) where.date.gte = new Date(dateFrom);
    if (dateTo) where.date.lte = new Date(dateTo);
  }

  const [data, total] = await Promise.all([
    prisma.warehouseDocument.findMany({
      where,
      skip,
      take: limit,
      orderBy: { date: 'desc' },
      include: { items: { include: { product: true, barcode: true } } },
    }),
    prisma.warehouseDocument.count({ where }),
  ]);

  return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
}

export async function getDocumentById(id: string) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  return prisma.warehouseDocument.findFirst({
    where,
    include: { items: { include: { product: true, barcode: true } }, order: true },
  });
}

export async function createDocument(input: CreateDocumentInput) {
  const tenantId = getTenantId();
  if (!tenantId) throw new Error('Brak kontekstu tenanta');

  const preparedItems = await prepareDocumentItems(tenantId, input.items, true, input.type);
  const context = getTenantContext();

  return prisma.$transaction(async (tx) => {
    const number = await generateDocumentNumber(tx, tenantId, input.type);

    return tx.warehouseDocument.create({
      data: {
        tenantId,
        number,
        type: input.type,
        status: 'DRAFT',
        date: input.date ? new Date(input.date) : new Date(),
        description: input.description,
        orderId: input.orderId,
        createdByUserId: context?.userId,
        isAutoGenerated: input.isAutoGenerated ?? false,
        metadataJson: input.metadataJson,
        items: {
          create: preparedItems.map((item) => ({
            productId: item.productId,
            quantity: item.quantity,
            systemQuantity: item.systemQuantity ?? null,
            barcodeId: item.barcodeId,
            scannedEan: item.scannedEan,
            baseQuantity: item.baseQuantity,
            quantityMultiplier: item.quantityMultiplier,
            unitPrice: item.unitPrice,
            notes: item.notes,
            reservationId: item.reservationId,
          })),
        },
      },
      include: { items: { include: { product: true, barcode: true } } },
    });
  });
}

export async function createWzForOrder(orderId: string): Promise<CreateWzForOrderResult> {
  const contextTenantId = getTenantId();
  const order = await prisma.order.findFirst({
    where: {
      id: orderId,
      ...(contextTenantId ? { shop: { tenantId: contextTenantId } } : {}),
    },
    include: {
      shop: true,
      items: true,
    },
  });

  if (!order) throw new Error('Zamówienie nie znalezione');

  const existingDocument = await prisma.warehouseDocument.findFirst({
    where: {
      tenantId: order.shop.tenantId,
      orderId,
      type: 'WZ',
      status: { not: 'CANCELLED' },
    },
    include: { items: { include: { product: true, barcode: true } }, order: true },
  });

  if (existingDocument) {
    return { document: existingDocument, created: false, skippedReason: 'WZ dla tego zamówienia już istnieje' };
  }

  if (order.items.length === 0) {
    return { document: null, created: false, skippedReason: 'Zamówienie nie ma pozycji' };
  }

  let activeReservations = await prisma.warehouseReservation.findMany({
    where: {
      tenantId: order.shop.tenantId,
      orderId: order.id,
      status: 'ACTIVE',
    },
    include: {
      warehouseProduct: true,
      orderItem: true,
    },
    orderBy: { createdAt: 'asc' },
  });

  let reservationResult: Awaited<ReturnType<typeof reserveOrder>> | null = null;
  if (activeReservations.length === 0) {
    reservationResult = await reserveOrder(order.id);
    activeReservations = await prisma.warehouseReservation.findMany({
      where: {
        tenantId: order.shop.tenantId,
        orderId: order.id,
        status: 'ACTIVE',
      },
      include: {
        warehouseProduct: true,
        orderItem: true,
      },
      orderBy: { createdAt: 'asc' },
    });
  }

  if (activeReservations.length === 0) {
    return { document: null, created: false, skippedReason: 'Brak aktywnych rezerwacji do wydania WZ' };
  }

  const stockWarning = Boolean(
    reservationResult && (reservationResult.partial > 0 || reservationResult.missingMapping > 0 || reservationResult.missingStock > 0),
  );
  const settings = await getWarehouseSettings(order.shop.tenantId);
  const shippingInfo = extractOrderShippingInfo(order.payloadJson, order.currency);
  const shippingDescription = buildShippingInfoDescription(shippingInfo);
  const metadata: Record<string, unknown> = {};
  if (stockWarning) {
    metadata.stockWarning = true;
    metadata.reservationIssues = JSON.parse(JSON.stringify(reservationResult?.issues ?? []));
  }
  if (shippingInfo) {
    metadata.shipping = shippingInfo;
  }

  const document = await prisma.$transaction(async (tx) => {
    const number = await generateDocumentNumber(tx, order.shop.tenantId, 'WZ');

    const createdDocument = await tx.warehouseDocument.create({
      data: {
        tenantId: order.shop.tenantId,
        number,
        type: 'WZ',
        status: settings.autoConfirmWzOnOrder ? 'CONFIRMED' : 'DRAFT',
        date: new Date(),
        description: [
          `WZ automatyczne dla zamówienia ${order.orderReference}`,
          shippingDescription,
        ].filter(Boolean).join('. '),
        orderId: order.id,
        isAutoGenerated: true,
        metadataJson: Object.keys(metadata).length > 0 ? JSON.parse(JSON.stringify(metadata)) : undefined,
        confirmedAt: settings.autoConfirmWzOnOrder ? new Date() : undefined,
        items: {
          create: activeReservations.map((reservation) => ({
            productId: reservation.warehouseProductId,
            quantity: reservation.quantity,
            reservationId: reservation.id,
            notes: `Zamówienie ${order.orderReference}`,
          })),
        },
      },
      include: { items: { include: { product: true, barcode: true } }, order: true },
    });

    if (settings.autoConfirmWzOnOrder) {
      await consumeDocumentReservations(tx, createdDocument.items);
    }

    return createdDocument;
  });

  return { document, created: true };
}

export async function updateDocument(id: string, input: UpdateDocumentInput) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const data: any = {};
  if (input.date !== undefined) data.date = new Date(input.date);
  if (input.description !== undefined) data.description = input.description;
  if (input.orderId !== undefined) data.orderId = input.orderId;

  if (input.items) {
    const preparedItems = await prepareDocumentItems(tenantId ?? doc.tenantId, input.items, true, doc.type as DocumentType);

    await prisma.warehouseDocumentItem.deleteMany({ where: { documentId: id } });
    data.items = {
      create: preparedItems.map((item) => ({
        productId: item.productId,
        quantity: item.quantity,
        systemQuantity: item.systemQuantity ?? null,
        barcodeId: item.barcodeId,
        scannedEan: item.scannedEan,
        baseQuantity: item.baseQuantity,
        quantityMultiplier: item.quantityMultiplier,
        unitPrice: item.unitPrice,
        notes: item.notes,
        reservationId: item.reservationId,
      })),
    };
  }

  return prisma.warehouseDocument.update({
    where: { id },
    data,
    include: { items: { include: { product: true, barcode: true } } },
  });
}

export async function mergeDocumentItem(documentId: string, input: DocumentItemInput) {
  const tenantId = getTenantId();
  const where: any = { id: documentId };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const [preparedItem] = await prepareDocumentItems(tenantId ?? doc.tenantId, [input], true, doc.type as DocumentType);
  if (!preparedItem) throw new Error('Pozycja dokumentu jest wymagana');

  const isInventory = doc.type === 'INW';

  const updatedDocument = await prisma.$transaction(async (tx) => {
    const existingItem = await tx.warehouseDocumentItem.findFirst({
      where: {
        documentId,
        productId: preparedItem.productId,
        ...(isInventory ? {} : { barcodeId: preparedItem.barcodeId ?? null }),
      },
    });

    if (existingItem) {
      if (isInventory) {
        await tx.warehouseDocumentItem.update({
          where: { id: existingItem.id },
          data: {
            quantity: preparedItem.quantity,
            systemQuantity: preparedItem.systemQuantity ?? null,
            scannedEan: preparedItem.scannedEan ?? existingItem.scannedEan,
            notes: preparedItem.notes ?? existingItem.notes,
          },
        });
      } else {
        await tx.warehouseDocumentItem.update({
          where: { id: existingItem.id },
          data: {
            quantity: new Prisma.Decimal(existingItem.quantity).plus(preparedItem.quantity),
            baseQuantity:
              existingItem.baseQuantity || preparedItem.baseQuantity
                ? new Prisma.Decimal(existingItem.baseQuantity ?? 0).plus(preparedItem.baseQuantity ?? 0)
                : null,
            quantityMultiplier: existingItem.quantityMultiplier ?? preparedItem.quantityMultiplier,
            scannedEan: existingItem.scannedEan ?? preparedItem.scannedEan,
            unitPrice: existingItem.unitPrice ?? preparedItem.unitPrice,
            notes: existingItem.notes || preparedItem.notes,
          },
        });
      }
    } else {
      await tx.warehouseDocumentItem.create({
        data: {
          documentId,
          productId: preparedItem.productId,
          quantity: preparedItem.quantity,
          systemQuantity: preparedItem.systemQuantity ?? null,
          barcodeId: preparedItem.barcodeId,
          scannedEan: preparedItem.scannedEan,
          baseQuantity: preparedItem.baseQuantity,
          quantityMultiplier: preparedItem.quantityMultiplier,
          unitPrice: preparedItem.unitPrice,
          notes: preparedItem.notes,
          reservationId: preparedItem.reservationId,
        },
      });
    }

    return tx.warehouseDocument.findUnique({
      where: { id: documentId },
      include: { items: { include: { product: true, barcode: true } }, order: true },
    });
  });

  return updatedDocument;
}

export async function updateDocumentItem(documentId: string, itemId: string, input: UpdateDocumentItemInput) {
  const tenantId = getTenantId();
  const documentWhere: any = { id: documentId };
  if (tenantId) documentWhere.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where: documentWhere });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const item = await prisma.warehouseDocumentItem.findFirst({ where: { id: itemId, documentId } });
  if (!item) throw new Error('Pozycja dokumentu nie znaleziona');

  const isInventory = doc.type === 'INW';

  const data: Prisma.WarehouseDocumentItemUpdateInput = {};
  if (input.quantity !== undefined) {
    if (isInventory) {
      if (input.quantity < 0) throw new Error('Stan policzony nie może być ujemny');
    } else if (input.quantity <= 0) {
      throw new Error('Ilość pozycji musi być większa od 0');
    }
    data.quantity = input.quantity;
  }
  if (input.systemQuantity !== undefined) {
    if (!isInventory) throw new Error('Stan systemowy można aktualizować tylko w dokumencie INW');
    if (input.systemQuantity !== null && input.systemQuantity < 0) throw new Error('Stan systemowy nie może być ujemny');
    data.systemQuantity = input.systemQuantity;
  }
  if (input.baseQuantity !== undefined) {
    if (input.baseQuantity !== null && input.baseQuantity <= 0) throw new Error('Ilość bazowa musi być większa od 0');
    data.baseQuantity = input.baseQuantity;
  }
  if (input.quantityMultiplier !== undefined) {
    if (input.quantityMultiplier !== null && input.quantityMultiplier <= 0) throw new Error('Przelicznik EAN musi być większy od 0');
    data.quantityMultiplier = input.quantityMultiplier;
  }
  if (input.unitPrice !== undefined) {
    if (input.unitPrice !== null && input.unitPrice < 0) throw new Error('Cena pozycji nie może być ujemna');
    data.unitPrice = input.unitPrice;
  }
  if (input.notes !== undefined) data.notes = input.notes;

  await prisma.warehouseDocumentItem.update({
    where: { id: itemId },
    data,
  });

  return prisma.warehouseDocument.findUnique({
    where: { id: documentId },
    include: { items: { include: { product: true, barcode: true } }, order: true },
  });
}

export async function deleteDocumentItem(documentId: string, itemId: string) {
  const tenantId = getTenantId();
  const documentWhere: any = { id: documentId };
  if (tenantId) documentWhere.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where: documentWhere });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można edytować tylko dokumenty w statusie DRAFT');

  const item = await prisma.warehouseDocumentItem.findFirst({ where: { id: itemId, documentId } });
  if (!item) throw new Error('Pozycja dokumentu nie znaleziona');

  await prisma.warehouseDocumentItem.delete({ where: { id: itemId } });

  return prisma.warehouseDocument.findUnique({
    where: { id: documentId },
    include: { items: { include: { product: true, barcode: true } }, order: true },
  });
}

export async function confirmDocument(id: string) {
  const tenantId = getTenantId();
  const context = getTenantContext();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({
    where,
    include: { items: { include: { product: true } } },
  });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Tylko dokumenty DRAFT można zatwierdzić');

  if (doc.items.length === 0) throw new Error('Dokument nie ma żadnych pozycji');

  await assertCanConfirmWithoutNegativeStock(doc.tenantId, doc.type, doc.items);

  const confirmedDocument = await prisma.$transaction(async (tx) => {
    await applyIncomingPurchaseCosts(tx, doc.type, doc.items);
    await applyStockDeltas(tx, doc.type, doc.items);
    await consumeDocumentReservations(tx, doc.items);

    return tx.warehouseDocument.update({
      where: { id },
      data: {
        status: 'CONFIRMED',
        confirmedAt: new Date(),
        confirmedByUserId: context?.userId,
      },
      include: { items: { include: { product: true, barcode: true } } },
    });
  });

  await syncStockForProducts(
    doc.items.map((item) => item.productId),
    'DOCUMENT_CONFIRM',
    id,
  );

  return confirmedDocument;
}

async function assertCanConfirmWithoutNegativeStock(
  tenantId: string,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; systemQuantity?: Prisma.Decimal | null; reservationId?: string | null; product: { name: string; unit: string } }>,
) {
  if (type === 'INW') {
    for (const item of items) {
      if (Number(item.quantity) < 0) {
        throw new Error(`Stan policzony produktu "${item.product.name}" nie może być ujemny`);
      }
    }
    return;
  }

  if (!['WZ', 'RW'].includes(type)) return;

  const settings = await getWarehouseSettings(tenantId);
  if (settings.allowNegativeStock) return;

  const requestedByProduct = new Map<string, { quantity: number; name: string; unit: string }>();

  for (const item of items) {
    if (type === 'WZ' && item.reservationId) continue;

    const existing = requestedByProduct.get(item.productId);
    const quantity = Number(item.quantity);

    if (existing) {
      existing.quantity += quantity;
    } else {
      requestedByProduct.set(item.productId, {
        quantity,
        name: item.product.name,
        unit: item.product.unit,
      });
    }
  }

  for (const [productId, requested] of requestedByProduct) {
    const stock = await calculateProductStock(tenantId, productId);
    const requestedQuantity = requested.quantity;
    const nextStock = stock - requestedQuantity;

    if (nextStock < 0) {
      throw new Error(
        `Niewystarczający stan produktu "${requested.name}": dostępne ${stock} ${requested.unit}, wymagane ${requestedQuantity} ${requested.unit}`,
      );
    }
  }
}

async function getWarehouseSettings(tenantId: string) {
  const tenant = await prisma.tenant.findUnique({
    where: { id: tenantId },
    select: { limitsJson: true },
  });

  const limits = tenant?.limitsJson as any;
  return {
    allowNegativeStock: limits?.warehouse?.allowNegativeStock !== false,
    autoCreateWzOnOrder: limits?.warehouse?.autoCreateWzOnOrder !== false,
    autoConfirmWzOnOrder: limits?.warehouse?.autoConfirmWzOnOrder === true,
  };
}

export async function shouldAutoCreateWzForTenant(tenantId: string) {
  const settings = await getWarehouseSettings(tenantId);
  return settings.autoCreateWzOnOrder;
}

async function calculateProductStock(tenantId: string, productId: string) {
  const [items, activeReservations] = await Promise.all([
    prisma.warehouseDocumentItem.findMany({
      where: {
        productId,
        document: {
          tenantId,
          status: 'CONFIRMED',
        },
      },
      include: {
        document: true,
      },
    }),
    prisma.warehouseReservation.findMany({
      where: {
        tenantId,
        warehouseProductId: productId,
        status: 'ACTIVE',
      },
      select: { quantity: true },
    }),
  ]);

  const documentStock = items.reduce((stock, item) => {
    const quantity = Number(item.quantity);
    if (['PZ', 'PW'].includes(item.document.type)) return stock + quantity;
    if (['WZ', 'RW'].includes(item.document.type)) return stock - quantity;
    if (item.document.type === 'INW') {
      const systemQuantity = item.systemQuantity != null ? Number(item.systemQuantity) : 0;
      return stock + (quantity - systemQuantity);
    }
    return stock;
  }, 0);
  const reservedStock = activeReservations.reduce((sum, reservation) => sum + Number(reservation.quantity), 0);
  return documentStock - reservedStock;
}

export async function cancelDocument(id: string, input: CancelDocumentInput = {}) {
  const tenantId = getTenantId();
  const context = getTenantContext();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({
    where,
    include: { items: true },
  });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status === 'CANCELLED') throw new Error('Dokument jest już anulowany');

  const cancelledDocument = await prisma.$transaction(async (tx) => {
    if (doc.status === 'CONFIRMED') {
      await applyStockDeltas(tx, doc.type, doc.items, true);
      await releaseDocumentReservations(tx, doc.items);
    }

    return tx.warehouseDocument.update({
      where: { id },
      data: {
        status: 'CANCELLED',
        cancelledAt: new Date(),
        cancelledByUserId: context?.userId,
        cancelReason: input.reason,
      },
      include: { items: { include: { product: true, barcode: true } } },
    });
  });

  if (doc.status === 'CONFIRMED') {
    await syncStockForProducts(
      doc.items.map((item) => item.productId),
      'DOCUMENT_CANCEL',
      id,
    );
  }

  return cancelledDocument;
}

export async function deleteDocument(id: string) {
  const tenantId = getTenantId();
  const where: any = { id };
  if (tenantId) where.tenantId = tenantId;

  const doc = await prisma.warehouseDocument.findFirst({ where });
  if (!doc) throw new Error('Dokument nie znaleziony');
  if (doc.status !== 'DRAFT') throw new Error('Można usunąć tylko dokumenty w statusie DRAFT');

  return prisma.warehouseDocument.delete({ where: { id } });
}

async function prepareDocumentItems(
  tenantId: string,
  items: DocumentItemInput[],
  requireActiveProduct: boolean,
  type?: DocumentType,
): Promise<PreparedDocumentItem[]> {
  const isInventory = type === 'INW';
  const preparedItems: PreparedDocumentItem[] = [];
  const productIds = Array.from(new Set(items.map((item) => item.productId).filter(Boolean)));
  const barcodeIds = Array.from(new Set(items.map((item) => item.barcodeId).filter(Boolean) as string[]));

  if (isInventory) {
    const seen = new Set<string>();
    for (const item of items) {
      if (seen.has(item.productId)) {
        throw new Error('W dokumencie INW każdy produkt może wystąpić tylko raz');
      }
      seen.add(item.productId);
    }
  }

  const productSelect = isInventory
    ? { id: true, name: true, isActive: true, currentStock: true }
    : { id: true, name: true, isActive: true };

  const [products, barcodes] = await Promise.all([
    prisma.warehouseProduct.findMany({
      where: { id: { in: productIds }, tenantId },
      select: productSelect,
    }),
    barcodeIds.length > 0
      ? prisma.warehouseProductBarcode.findMany({
          where: { id: { in: barcodeIds }, tenantId },
          select: {
            id: true,
            warehouseProductId: true,
            ean: true,
            quantityMultiplier: true,
            isActive: true,
          },
        })
      : Promise.resolve([]),
  ]);

  const productById = new Map(products.map((product) => [product.id, product as typeof product & { currentStock?: Prisma.Decimal }]));
  const barcodeById = new Map(barcodes.map((barcode) => [barcode.id, barcode]));

  for (const item of items) {
    const product = productById.get(item.productId);
    if (!product) throw new Error(`Produkt ${item.productId} nie znaleziony`);
    if (requireActiveProduct && !product.isActive) throw new Error(`Produkt "${product.name}" jest nieaktywny`);

    let scannedEan = item.scannedEan?.trim() || undefined;
    let quantityMultiplier = item.quantityMultiplier;
    const barcodeId = item.barcodeId;

    if (barcodeId) {
      const barcode = barcodeById.get(barcodeId);
      if (!barcode) throw new Error(`Kod EAN ${barcodeId} nie znaleziony dla produktu "${product.name}"`);
      if (barcode.warehouseProductId !== item.productId) {
        throw new Error(`Kod EAN ${barcodeId} nie znaleziony dla produktu "${product.name}"`);
      }
      if (!barcode.isActive) throw new Error(`Kod EAN "${barcode.ean}" jest nieaktywny`);
      scannedEan = scannedEan ?? barcode.ean;
      quantityMultiplier = quantityMultiplier ?? Number(barcode.quantityMultiplier);
    }

    const minQuantity = isInventory ? 0 : 0; // próg dolny włącznie — INW dopuszcza 0
    const requireStrictPositive = !isInventory;

    const baseQuantity = item.baseQuantity ?? item.quantity;
    if (baseQuantity === undefined || (requireStrictPositive ? baseQuantity <= 0 : baseQuantity < minQuantity)) {
      throw new Error(isInventory ? 'Stan policzony nie może być ujemny' : 'Ilość pozycji musi być większa od 0');
    }

    quantityMultiplier = quantityMultiplier ?? 1;
    if (quantityMultiplier <= 0) throw new Error('Przelicznik EAN musi być większy od 0');

    const quantity = item.quantity ?? baseQuantity * quantityMultiplier;
    if (requireStrictPositive ? quantity <= 0 : quantity < minQuantity) {
      throw new Error(isInventory ? 'Stan policzony nie może być ujemny' : 'Ilość pozycji musi być większa od 0');
    }

    let systemQuantity: number | null | undefined;
    if (isInventory) {
      if (item.systemQuantity === null || item.systemQuantity === undefined) {
        systemQuantity = Number(product.currentStock ?? 0);
      } else {
        systemQuantity = Number(item.systemQuantity);
        if (!Number.isFinite(systemQuantity)) {
          throw new Error('Stan systemowy jest nieprawidłowy');
        }
      }
    }

    preparedItems.push({
      productId: item.productId,
      quantity,
      systemQuantity,
      barcodeId,
      scannedEan,
      baseQuantity,
      quantityMultiplier,
      unitPrice: item.unitPrice,
      notes: item.notes,
      reservationId: item.reservationId ?? null,
    });
  }

  return preparedItems;
}

async function applyStockDeltas(
  tx: Prisma.TransactionClient,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; systemQuantity?: Prisma.Decimal | null; reservationId?: string | null }>,
  reverse = false,
) {
  if (type === 'INW') {
    const deltas = new Map<string, Prisma.Decimal>();
    for (const item of items) {
      const counted = new Prisma.Decimal(item.quantity);
      const system = new Prisma.Decimal(item.systemQuantity ?? 0);
      const delta = reverse ? system.minus(counted) : counted.minus(system);
      deltas.set(item.productId, (deltas.get(item.productId) ?? new Prisma.Decimal(0)).plus(delta));
    }
    for (const [productId, delta] of deltas) {
      if (delta.equals(0)) continue;
      await tx.warehouseProduct.update({
        where: { id: productId },
        data: { currentStock: { increment: delta } },
      });
    }
    return;
  }

  const baseSign = getStockDeltaSign(type);
  if (baseSign === 0) return;

  const sign = reverse ? -baseSign : baseSign;
  const deltas = new Map<string, Prisma.Decimal>();

  for (const item of items) {
    if (type === 'WZ' && item.reservationId) continue;

    const current = deltas.get(item.productId) ?? new Prisma.Decimal(0);
    deltas.set(item.productId, current.plus(item.quantity.mul(sign)));
  }

  for (const [productId, delta] of deltas) {
    await tx.warehouseProduct.update({
      where: { id: productId },
      data: { currentStock: { increment: delta } },
    });
  }
}

async function applyIncomingPurchaseCosts(
  tx: Prisma.TransactionClient,
  type: DocumentType,
  items: Array<{ productId: string; quantity: Prisma.Decimal; unitPrice?: Prisma.Decimal | null }>,
) {
  if (type !== 'PZ') return;

  const incomingByProduct = new Map<string, { quantity: Prisma.Decimal; value: Prisma.Decimal }>();
  for (const item of items) {
    if (item.unitPrice === null || item.unitPrice === undefined) continue;
    const quantity = new Prisma.Decimal(item.quantity);
    if (quantity.lte(0)) continue;
    const value = quantity.mul(item.unitPrice);
    const current = incomingByProduct.get(item.productId) ?? {
      quantity: new Prisma.Decimal(0),
      value: new Prisma.Decimal(0),
    };
    incomingByProduct.set(item.productId, {
      quantity: current.quantity.plus(quantity),
      value: current.value.plus(value),
    });
  }

  for (const [productId, incoming] of incomingByProduct) {
    const product = await tx.warehouseProduct.findUnique({
      where: { id: productId },
      select: { currentStock: true, averagePurchaseCost: true, purchasePrice: true },
    });
    if (!product) continue;

    const currentStock = Prisma.Decimal.max(new Prisma.Decimal(product.currentStock), new Prisma.Decimal(0));
    const currentCost = new Prisma.Decimal(product.averagePurchaseCost ?? product.purchasePrice ?? 0);
    const nextStock = currentStock.plus(incoming.quantity);
    const nextCost = currentStock.gt(0) && currentCost.gt(0)
      ? currentStock.mul(currentCost).plus(incoming.value).div(nextStock)
      : incoming.value.div(incoming.quantity);

    await tx.warehouseProduct.update({
      where: { id: productId },
      data: { averagePurchaseCost: new Prisma.Decimal(nextCost.toFixed(2)) },
    });
  }
}

function getStockDeltaSign(type: DocumentType) {
  if (STOCK_INCOMING_TYPES.includes(type)) return 1;
  if (STOCK_OUTGOING_TYPES.includes(type)) return -1;
  return 0;
}

// ─── Numeracja dokumentów ─────────────────────────────────────────────────────

async function generateDocumentNumber(
  tx: Prisma.TransactionClient,
  tenantId: string,
  type: DocumentType,
): Promise<string> {
  const year = new Date().getFullYear();
  const prefix = `${type}/${year}/`;
  const lockKey = `${tenantId}:${type}:${year}`;

  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${lockKey}))`;

  // Znajdź najwyższy numer w tym roku dla tego tenanta i typu
  const last = await tx.warehouseDocument.findFirst({
    where: { tenantId, number: { startsWith: prefix } },
    orderBy: { number: 'desc' },
  });

  let seq = 1;
  if (last) {
    const parts = last.number.split('/');
    const lastSeq = parseInt(parts[2], 10);
    if (!isNaN(lastSeq)) seq = lastSeq + 1;
  }

  return `${prefix}${String(seq).padStart(3, '0')}`;
}
